<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();
$userSession = $session->getSession('user');
$configSession = $session->getSession('config');
$bActionStatus = isset($configSession->bulk_action)?strtolower($configSession->bulk_action):'off';
?>

<?php if (!empty($bulkActions) && $bActionStatus == 'on') {?>
  <div class="col-md-3">
        <select name="bulk_actions" id="bulk_actions" class="form-control" onchange="chooseAction(this.value);">
            <option value="0">Select Bulk Action</option>
            <?php foreach($bulkActions as $bulkAction) { ?>
                <option value="<?php echo $bulkAction['action_id'];?>"><?php echo $bulkAction['action_name'];?></option>
            <?php } ?>
        </select>
  </div>
<?php } ?>
<!-- Modal -->
    <div class="modal fade" id="automaticModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header" style="border-bottom:0;">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div style="display:none;" id="automaticModalForm"></div>
                    <!--<p class="text-center">Are you sure you want to apply this action?</p>-->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="applyAction('automatic')">Apply</button>
                    <input type="hidden" value="" id="categoryIdtoDelete"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
<!-- Modal -->
    <div class="modal fade" id="manualModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header" style="border-bottom:0;">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div style="display:none;" id="manualModalForm"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="applyAction('manual')">Apply</button>
                    <input type="hidden" value="" id="categoryIdtoDelete"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
<!-- End page wrapper -->
<style>
.ag-theme-material .ag-icon {
    color: #CCC;
}
.ag-theme-material .ag-icon-checkbox-checked {
    color: #5cb85c;
}

</style>