<?php 
use Session\Container\SessionContainer;
$session = new SessionContainer();
$msg = $session->getSession('import_settings');
$messageStatus = $msg->msg;
$session->clearSession('import_settings');
$title = "Import Settings";
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
      <li><span>Settings</span></li>
      <li class="active"><span><?php echo $this->escapeHtml($title); ?></span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body"> 
        <div class="card">
            <div class="card-header">
                <h4><?php echo $this->escapeHtml($title); ?></h4>
            </div>
            <div class="card-body">
                <p class="alert alert-success" id="alert" <?php if($messageStatus != 'SUC'){ ?> style="display:none;" <?php } ?> >
                    <i class="lnr icon-trash3 close" data-dismiss="alert"></i> Import Settings saved Successfully!!!
                </p>
                <div class="card">
                    <form method="POST" id="importFields" class="form-horizontal row-border">
                        <div class="card-header">
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Form Name</label>
                                <label class="col-sm-3 col-form-label">File Type</label>
                                <label class="col-sm-5 col-form-label">Fields</label>   
                            </div>
                        </div>
                        <div class="card-body"> 
                            <?=$fields;?>
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                                <div class="col-sm-8">
                                   <textarea id="reason" class="form-control" placeholder="Reason for change" name="reason"></textarea>
                                   <div id="forReason" class="error"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <a class="btn btn-default pull-right" href="<?=isset($_SERVER['HTTP_REFERER'])? $_SERVER['HTTP_REFERER']:'#';?>">Cancel</a>
                            <button class="btn btn-primary" id="import_form_submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
    window.setInterval(function(){
      $('#alert').removeClass('alert-success').hide().html('');
    }, 3000);
    
    $("#import_form_submit").click(function(){
        var count = 0;
        if ($('#reason').val()=='') {
            $("#forReason").html(messageJSON.MSG_FIELD_EMPTY.replace('#fieldName','Reason for change'));
            count++; 
        }
        
        if (count == 0) {
            $('#importFields').submit();    
        }
        return false;
    });
});
</script>

