<?php
$tracker_details = $trackerResults['tracker_details'];
$forms = $trackerResults['forms'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name - Access Settings";
$this->headTitle($title);

$id = 0;
$form_id = 0;
$form_ids = 0;
$wfid = 0;
$roleid = 0;
$wfids = 0;
$roleids = 0; //

$wfs = $resultset[0];
$roles = $resultset[1];
$wfs_arr = array();
$wfs_arravalues = array();
$formdetails = array();
$formdetails_arr = array();

foreach ($wfs as $key => $value) {
    $workflow_id = $value->workflow_id;
    $wf_name = $value->workflow_name;
    $form_name = $value->form_name;
    $role_id = $value->role_id;
    if ($role_id == null) {
        $role_id = 0;
    }
    $wfs_arr[$form_name]['id'] = $value->form_id;
    if (!array_key_exists($wf_name, $wfs_arr)) {
        $wfs_arr[$form_name][$wf_name] = $workflow_id;
    }
    if (!in_array($form_name, $formdetails)) {
        $formdetails[] = $form_name;
    }
    $wfs_arravalues[$wf_name][] = $value;
    $formdetails_arr[$form_name][$wf_name][$role_id] = $value;
    if ($role_id == 0) {
        $formdetails_arr[$form_name][$wf_name] = array();
    }
}
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Settings</span></li>
        <li><span>Access Settings</span></li>
        <li class="active"><span>Record Access Settings</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">        
            <div class="card card-default" >
                <div class="card-header">
                    <b>Record Access Settings</b>
                </div>
                <div class="card-body">
                    <?php
                    $id = 1;
                    $form_name='';

                    foreach ($wfs_arr as $key_f_name => $value_wf) { 
                        if (count(array_slice($value_wf, 1)) > 0) { ?>
                            <div class="card card-default">
                                <div class="card-body">
                                    <?php
                                    $form_name = $key_f_name;
                                    echo "<h6>$key_f_name</h6><hr/>";
                                    $wf_details_arr = $value_wf;
                                    $form_arr = $formdetails_arr[$key_f_name];
                                    ?>

                                    <table id="accessdata_insert_delete_<?php echo $id ?>"  class="table table-striped display stripe row-border order-column" cellspacing="0" width="100%">
                                        <thead>
                                        <tr>
                                            <th>Role Name</th>
                                            <th>Can Insert</th>
                                            <th>Can Delete</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody id='recordsbody'>
                                        <?php
                                        if (array_key_exists(0, $roles)) {
                                        foreach ($roles as $key_role_arr => $value_role_arr) {
                                        $role_id = $value_role_arr->rid;
                                        $group_name = $value_role_arr->role_name;
                                        $group_archived = $value_role_arr->archived;
                                        if ($group_archived == 0) {
                                        $can_read = "";
                                        $can_insert = "";
                                        $can_delete = "";
                                        foreach ($form_arr as $key_wf_name => $group_access_details) {
                                        $workflow_id = $wf_details_arr[$key_wf_name];
                                        $form_id=$wf_details_arr['id'];
                                        $workflow_name = $key_wf_name;
                                        $can_update = "";


                                        if (array_key_exists($role_id, $group_access_details)) {
                                            $access_details_arr = $group_access_details[$role_id];

                                            $can_insert = $access_details_arr->can_insert;
                                            $can_delete = $access_details_arr->can_delete;
                                            }
                                        }
                                        ?>
                                        <tr>
                                            <td> <?=$group_name;?> </td>
                                            <td>
                                                <?php
                                                if ($group_name == "Administrator" || $group_name == "SuperAdmin") {
                                                echo "Full Access";
                                                } else {
                                                ?>
                                                <select type="text" placeholder="Add Option" class="form-control" id="id_can_insert_<?= $role_id ?>_<?= $form_id; ?>">';
                                                    <option value="">Select option</option>
                                                    <option value="Yes" <?php
                                                            if ($can_insert == "Yes") {
                                                            echo 'selected';
                                                            }
                                                            ?>>Yes</option>
                                                    <option value="No" <?php
                                                            if ($can_insert == "No") {
                                                            echo 'selected';
                                                            }
                                                            ?>>No</option>
                                                </select>
                                                <?php } ?>
                                            </td>
                                            <td>
                                                <?php
                                                if ($group_name == "Administrator" || $group_name == "SuperAdmin" ) {
                                                echo "Full Access";
                                                } else {
                                                ?>
                                                <select type="text" placeholder="Add Option" class="form-control"  id="id_can_delete_<?= $role_id ?>_<?= $form_id; ?>" required:true>';
                                                    <option value="">Select option</option>
                                                    <option value="Yes" <?php
                                                            if ($can_delete == "Yes") {
                                                            echo 'selected';
                                                            }
                                                            ?>>Yes</option>
                                                    <option value="No" <?php
                                                            if ($can_delete == "No") {
                                                            echo 'selected';
                                                            }
                                                            ?>>No</option>
                                                </select>
                                                <?php } ?>
                                            </td>
                                            <td>
                                                <?php
                                                if ($group_name != "Administrator" || $group_name == "SuperAdmin") {
                                                ?>
                                                <div id="status_<?= $role_id ?>_<?= $form_id; ?>"></div>
                                                <button onclick="save_role_settings('<?= $role_id ?>','<?= $form_id ?>')" type="button" class="btn btn-primary">Save</button>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                        <?php
                                        }
                                        }
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                    <?php
                            $id++;
                           
                        }
                    }
                    if (count($wfs_arr) == 0) {
                    echo "No forms and workflows exists";
                    }
                    ?>
                        </div>
                    </div>
                </div>
</div>
     
    <div class="modal fade" id="addcommentasreason" tabindex="-1" role="dialog" aria-labelledby="deleteUserModal" aria-hidden="true">        
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Reason for change</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>  
                        <div class="col-sm-7"> 
                            <textarea id="addcomment" class="form-control" placeholder="Reason for change" name="addcomment"></textarea>   
                            <span id="commenterror" style="display:none;color: red;">Please add reason for change</span>
                            <span id="status_for_reason"></span>
                        </div> 
                    </div>
                </div>
                <div style="clear:both"></div>
                <div class="modal-footer">
                   <button onclick="reasonforchange()" type="button" class="btn btn-primary">Save</button>
                   <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

<!-- Content Section End -->

<script>
    
    role_id=0;
    form_id=0;
    workflow_id=0;
    action_name=''
    $(document).ready(function() {


    $("table[id^='accessdata_insert_delete']").each(function () {
            var id=this.id;
            $("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                "columnDefs": [ {
                            "bSortable": false,
                            "targets"  : -1
                          }]
                // "bAutoWidth": false
            });
        });

        $("table[id^='accessdata_read']").each(function () {
            var id=this.id;
            $("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                "columnDefs": [ {
                            "bSortable": false,
                            "targets"  : -1
                          }]
                // "bAutoWidth": false
            });
        });
        // $.fn.dataTable.ext.errMode = 'throw';
        $("table[id^='accessdata_update']").each(function () {
            var id=this.id;
            $("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                "columnDefs": [ {
                            "bSortable": false,
                            "targets"  : -1
                          }]
               // "bAutoWidth": false
            });
        });
    });
    function save_role_settings(role_ids, form_ids){
        var can_insert = $("#id_can_insert_"+role_ids+"_"+form_ids).val();
        var can_delete = $("#id_can_delete_"+role_ids+"_"+form_ids).val();

        if(can_insert == ""  || can_delete == ""){
            $("#status_"+role_ids+"_"+form_ids).html('<font color="red">Select Values</font>');
            window.setTimeout("closeUserCreateAlert('status_"+role_ids+"_"+form_ids+"')", 3000);
            return false;
        } else {
            $('#addcommentasreason').modal('show');
            $('#commenterror').hide();
            $('#addcomment').val('');
            role_id=role_ids;
            form_id=form_ids; 
            action_name='insertdelete';
        }
        window.setTimeout("closeUserCreateAlert('status_"+role_ids+"_"+form_ids+"')", 5000);
    }
    function reasonforchange(){ 
        var tracker_id="<?php echo $tracker_id  ?>";
        if(action_name=='insertdelete'){
            if ($('#addcomment').val() == ''){
                $('#commenterror').show();
                return false;
            }
            $('#commenterror').hide();
            var can_insert = $("#id_can_insert_"+role_id+"_"+form_id).val();
            var can_delete = $("#id_can_delete_"+role_id+"_"+form_id).val();
            $("#status_"+role_id+"_"+form_id).html('processing...');

            if(can_insert == ""  || can_delete == ""){
                $("#addcommentasreason").modal('toggle');
                $("#status_"+role_id+"_"+form_id).html('<font color="red">Select Values</font>');
                window.setTimeout("closeUserCreateAlert('status_"+role_id+"_"+form_id+"')", 3000);
                return false;
            }
            var data = {
                can_insert : can_insert,
                can_delete: can_delete,
                role_id:role_id,
                form_id : form_id,
                comment:$('#addcomment').val()
            };

            var url= "/settings/saveRecordAccessSetting/"+tracker_id;
            $.post(url, data,function(respJson){ 
                var resp =JSON.parse(respJson);
                var responseCode = resp.responseCode;
                var errMessage = resp.errMessage;
                if(responseCode == 1){
                    $("#addcommentasreason").modal('toggle');
                    $('#commenterrorforsort').hide();
                    $("#status_"+role_id+"_"+form_id).html('<font color="#088A08">'+errMessage+'</font>');
                    window.setTimeout("closeUserCreateAlert('status_"+role_id+"_"+form_id+"')", 3000);
                }
                else{
                    $("#status").html('<font color="#cc0000">'+errMessage+'</font>');
                    window.setTimeout("closeUserCreateAlert('status_"+role_id+"_"+form_id+"')", 3000);
                }
            });
        }
    }
    function closeUserCreateAlert(id) {
        $("#"+id).html('');
    }
    function closeUserCreateAlert(id) {
        $("#"+id).html('');
    }
</script>


<style>
    th, td { white-space: nowrap; }

    div.dataTables_wrapper {
      width: 100%;
        margin: 0 auto;
    }


</style>