<?php
$tracker_details = $trackerResults['tracker_details'];
$forms = $trackerResults['forms'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name - Workflow Access Settings";
$this->headTitle($title);

$id = 0;
$form_id = 0;
$form_ids = 0;
$wfid = 0;
$roleid = 0;
$wfids = 0;
$roleids = 0;

$wfs = $resultset[0];
$roles = $resultset[1];
$wfs_arr = array();
$wfs_arravalues = array();
$formdetails = array();
$formdetails_arr = array();

foreach ($wfs as $key => $value) {
    $workflow_id = $value->workflow_id;
    $wf_name = $value->workflow_name;
    $form_name = $value->form_name;
    $role_id = $value->role_id;
    if ($role_id == null) {
        $role_id = 0;
    }
    $wfs_arr[$form_name]['id'] = $value->form_id; 
    if (!array_key_exists($wf_name, $wfs_arr)) {
        $wfs_arr[$form_name][$wf_name] = $workflow_id;
    }
    if (!in_array($form_name, $formdetails)) {
        $formdetails[] = $form_name;
    }
    $wfs_arravalues[$wf_name][] = $value;
    $formdetails_arr[$form_name][$wf_name][$role_id] = $value;
    if ($role_id == 0) {
        $formdetails_arr[$form_name][$wf_name] = array();
    }
}
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Settings</span></li>
        <li><span>Access Settings</span></li>
        <li class="active"><span>Workflow Access Settings</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">        
        <div class="card card-default" >
            <div  class="card-header"> <b>Workflow Access Settings</b></div>
            <div class="card-body">
                <?php
                $id = 1; $form_name=''; $form_id=0;

                foreach ($wfs_arr as $key_f_name => $value_wf) {
                    
                    if (count(array_slice($value_wf, 1)) > 0) { ?>
                        <?php
                            $form_name = $key_f_name;
                            $wf_details_arr = $value_wf;
                            $form_arr = $formdetails_arr[$key_f_name];
                        ?>
                        <div class="card card-default mb-3">
                            <div class="card-header"><h6><?=$form_name;?></h6></div>
                            <?php if (count($wf_details_arr) > 0) { ?>
                            
                                <div class="card-body">
                                    <?php echo "<h6>Read Settings</h6><hr/>"; ?>
                                    <table id="accessdata_read_<?php echo $id ?>" class="table table-striped display stripe row-border order-column" cellspacing="0" width="100%" >
                                        <thead>
                                            <tr>
                                                <th>Role Name</th>
                                                <?php
                                                foreach ($form_arr as $key_wf_name => $group_access_details) {

                                                    $workflow_id = $wf_details_arr[$key_wf_name];
                                                    $workflow_name = $key_wf_name;
                                                    echo "<th style='width:100px;'><h6>$workflow_name </h6></th>";
                                                }
                                                ?>
                                                <th></th>

                                            </tr>
                                        </thead>
                                        <tbody id="recordsbody">
                                            <?php
                                            if (array_key_exists(0, $roles)) {
                                            foreach ($roles as $key_role_arr => $value_role_arr) {
                                            $role_id = $value_role_arr->rid;
                                            $group_name = $value_role_arr->role_name;
                                            $group_archived = $value_role_arr->archived;
                                            if ($group_archived == 0) {
                                            ?>
                                            <tr>
                                                <td><?= $group_name ?></td>
                                                <?php
                                                foreach ($form_arr as $key_wf_name => $group_access_details) {
                                                    $workflow_id = isset($wf_details_arr[$key_wf_name])?$wf_details_arr[$key_wf_name]:0;
                                                    $form_id = $wf_details_arr['id'];
                                                    $workflow_name = $key_wf_name;
                                                    $can_read = "";


                                                    if (array_key_exists($role_id, $group_access_details)) {
                                                        $access_details_arr = $group_access_details[$role_id];

                                                        $can_read = $access_details_arr->can_read;
                                                    }
                                                    ?>
                                                    <td>
                                                        <?php
                                                        if ($group_name == "Administrator" || $group_name == "SuperAdmin") {
                                                        echo "Full Access";
                                                        } else {
                                                        ?>
                                                        <select type="text" placeholder="Add Option" class="form-control" required id="id_can_read_<?= $form_id ?>_<?= $role_id ?>_<?= $workflow_id; ?>">';
                                                            <option value="">Select option</option>
                                                            <option value="Yes" <?php
                                                                    if ($can_read == "Yes") {
                                                                    echo 'selected';
                                                                    }
                                                                    ?>>ALL</option>
                                                            <option value="No" <?php
                                                                    if ($can_read == "No") {
                                                                    echo 'selected';
                                                                    }
                                                                    ?>>NONE</option>
                                                        </select>
                                                        <?php } ?>
                                                    </td>
                                                <?php } ?>
                                                <td>
                                                    <?php
                                                    if ($group_name != "Administrator") {
                                                    ?>
                                                    <div id="status_read_<?= $form_id ?>_<?= $role_id ?>_<?= $workflow_id; ?>"></div>
                                                    <button onclick="save_read_settings('<?= $form_id ?>','<?= $role_id ?>','<?= $workflow_id ?>')" type="button" class="btn btn-primary">Save</button>
                                                    <?php } ?>
                                                </td>
                                            </tr>

                                            <?php
                                            }
                                            }
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>

                            <?php } ?>
                            <?php if (count($wf_details_arr) > 0) { ?>

                                    <div class="card-body">
                                        <?php echo "<h6>Update Settings</h6><hr/>"; ?>
                                        <table id="accessdata_update_<?php echo $id ?>" class="table table-striped display stripe row-border order-column" cellspacing="0" width="100%" >
                                            <thead>
                                                <tr>
                                                    <th>Role Name</th>
                                                    <?php
                                                    foreach ($form_arr as $key_wf_name => $group_access_details) {
                                                        $workflow_id = $wf_details_arr[$key_wf_name];
                                                        $workflow_name = $key_wf_name;
                                                        echo "<th style='width:100px;'><h6>$workflow_name </h6></th>";
                                                    }
                                                    ?>
                                                    <th></th>

                                                </tr>
                                            </thead>
                                            <tbody id="recordsbody">
                                                <?php
                                                if (array_key_exists(0, $roles)) {
                                                foreach ($roles as $key_role_arr => $value_role_arr) {
                                                $role_id = $value_role_arr->rid;
                                                $group_name = $value_role_arr->role_name;
                                                $group_archived = $value_role_arr->archived;
                                                if ($group_archived == 0) {
                                                ?>
                                                <tr>
                                                    <td><?= $group_name ?></td>
                                                    <?php
                                                    foreach ($form_arr as $key_wf_name => $group_access_details) {
                                                        $workflow_id = $wf_details_arr[$key_wf_name];
                                                        $form_id=$wf_details_arr['id'];
                                                        $workflow_name = $key_wf_name;
                                                        $can_update = "";


                                                        if (array_key_exists($role_id, $group_access_details)) {
                                                            $access_details_arr = $group_access_details[$role_id];

                                                            $can_update = $access_details_arr->can_update;
                                                        }
                                                        ?>
                                                        <td>
                                                            <?php
                                                            if ($group_name == "Administrator" || $group_name == "SuperAdmin") {
                                                            echo "Full Access";
                                                            } else {
                                                            ?>
                                                            <select type="text" placeholder="Add Option" class="form-control" required id="id_can_update_<?= $form_id ?>_<?= $role_id ?>_<?= $workflow_id; ?>">';
                                                                <option value="">Select option</option>
                                                                <option value="Yes" <?php
                                                                        if ($can_update == "Yes") {
                                                                        echo 'selected';
                                                                        }
                                                                        ?>>ALL</option>
                                                                <option value="No" <?php
                                                                        if ($can_update == "No") {
                                                                        echo 'selected';
                                                                        }
                                                                        ?>>NONE</option>
                                                                <option value="Self" <?php
                                                                        if ($can_update == "Self") {
                                                                        echo 'selected';
                                                                        }
                                                                        ?>>SELF</option>
                                                            </select>
                                                            <?php } ?>
                                                        </td>
                                                    <?php } ?>
                                                    <td>
                                                        <?php
                                                        if ($group_name != "Administrator") {
                                                        ?>
                                                        <div id="status_update_<?= $form_id ?>_<?= $role_id ?>_<?= $workflow_id; ?>"></div>
                                                        <button onclick="save_update_settings('<?= $form_id ?>','<?= $role_id ?>','<?= $workflow_id ?>')" type="button" class="btn btn-primary">Save</button>
                                                        <?php } ?>
                                                    </td>
                                                </tr>

                                                <?php
                                                }
                                                }
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                    </div>
                            <?php
                                  } else {
                                    echo "No workflows exists";
                                  }
                            ?>
                        </div>
                        <?php 
                        $id++;
                    }
                }
                if (count($wfs_arr) == 0) {
                    echo "No forms and workflows exists";
                }
                ?>
            </div>
        </div>
    </div>
</div>
     
    <div class="modal fade" id="addcommentasreason" tabindex="-1" role="dialog" aria-labelledby="deleteUserModal" aria-hidden="true">        
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Reason for change</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>  
                        <div class="col-sm-7"> 
                            <textarea id="addcomment" class="form-control" placeholder="Reason for change" name="addcomment"></textarea>   
                            <span id="commenterror" style="display:none;color: red;">Please add reason for change</span>
                            <span id="status_for_reason"></span>
                        </div> 
                    </div>
                </div>
                <div style="clear:both"></div>
                <div class="modal-footer">
                   <button onclick="reasonforchange()" type="button" class="btn btn-primary">Save</button>
                   <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

<!-- Content Section End -->

<script>
    
    role_id = 0;
    form_id = 0;
    workflow_id = 0;
    action_name=''
    $(document).ready(function() {


    $("table[id^='accessdata_insert_delete']").each(function () {
            var id=this.id;
            $("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                "columnDefs": [ {
                            "bSortable": false,
                            "targets"  : -1
                          }]
                // "bAutoWidth": false
            });
        });

        $("table[id^='accessdata_read']").each(function () {
            var id=this.id;
            $("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                "columnDefs": [ {
                            "bSortable": false,
                            "targets"  : -1
                          }]
                // "bAutoWidth": false
            });
        });
        // $.fn.dataTable.ext.errMode = 'throw';
        $("table[id^='accessdata_update']").each(function () {
            var id=this.id;
            $("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                "columnDefs": [ {
                            "bSortable": false,
                            "targets"  : -1
                          }]
               // "bAutoWidth": false
            });
        });
    });
    function save_role_settings(role_ids, form_ids){
        var can_insert = $("#id_can_insert_"+role_ids+"_"+form_ids).val();
        var can_delete = $("#id_can_delete_"+role_ids+"_"+form_ids).val();

        if(can_insert == ""  || can_delete == ""){
            $("#status_"+role_ids+"_"+form_ids).html('<font color="red">Select Values</font>');
            window.setTimeout("closeUserCreateAlert('status_"+role_ids+"_"+form_ids+"')", 3000);
            return false;
        } else {
            $('#addcommentasreason').modal('show');
            $('#commenterror').hide();
            $('#addcomment').val('');
            role_id=role_ids;
            form_id=form_ids; 
            action_name='insertdelete';
        }
        window.setTimeout("closeUserCreateAlert('status_"+role_ids+"_"+form_ids+"')", 5000);
    }
    function reasonforchange(){
         
        var tracker_id = "<?php echo $tracker_id;?>";
        if(action_name == 'read'){
            if ($('#addcomment').val() == ''){
                $('#commenterror').show();
                return false;
            }
            $('#commenterror').hide();
            var read=0;
            var workflow_ids = [];
            var can_reads=[];

            $("select[id^='id_can_read_"+form_id+"_"+role_id+"']").each(function () {
                var res=(this.id).split('_');
                var id=this.id;
                var can_read = $("#"+id).val();
                if( can_read == ""){
                    read++;
                } 
                workflow_ids.push(res[5]);
                can_reads.push(can_read);

            });
            $("#status_read_"+form_id+"_"+role_id+"_"+workflow_id).html('processing...');
            if( read > 0 ){
                $("#addcommentasreason").modal('toggle');
                $("#status_read_"+form_id+"_"+role_id+"_"+workflow_id).html('<font color="red">Select Values</font>');
                window.setTimeout("closeUserCreateAlert('status_read_"+form_id+"_"+role_id+"_"+workflow_id+"')", 3000);
                return false;
            }
            var data = {
                can_read: can_reads,
                role_id:role_id,
                form_id : form_id,
                workflow_id : workflow_ids,
                comment:$('#addcomment').val()
            };
            var url= "/settings/save_read_setting/"+tracker_id;
            $.post(url, data,function(respJson){
                var resp =JSON.parse(respJson);
                var responseCode = resp.responseCode;
                var errMessage = resp.errMessage;
                if(responseCode == 1){
                    $("#addcommentasreason").modal('toggle');
                    $("#status_read_"+form_id+"_"+role_id+"_"+workflow_id).html('<font color="#088A08">'+errMessage+'</font>');
                    window.setTimeout("closeUserCreateAlert('status_read_"+form_id+"_"+role_id+"_"+workflow_id+"')", 3000);
                }
                else{
                    $("#status_read_").html('<font color="#cc0000">'+errMessage+'</font>');
                    window.setTimeout("closeUserCreateAlert('status_read_"+form_id+"_"+role_id+"_"+workflow_id+"')", 3000);
                }
            });
        }
        if(action_name=='update'){
            if ($('#addcomment').val() == ''){
                $('#commenterror').show();
                return false;
            }
            $('#commenterror').hide();
            var update=0;
            var workflow_ids = [];
            var can_updates=[];
            $("select[id^='id_can_update_"+form_id+"_"+role_id+"']").each(function () {
                var res=(this.id).split('_');
                var id=this.id;
                var can_update = $("#"+id).val();
                if( can_update == ""){
                    update++;
                }
                workflow_ids.push(res[5]);
                can_updates.push(can_update);

            });
            $("#status_update_"+form_id+"_"+role_id+"_"+workflow_id).html('processing...');
            if( update > 0){
                $("#addcommentasreason").modal('toggle');
                $("#status_update_"+form_id+"_"+role_id+"_"+workflow_id).html('<font color="red">Select Values</font>');
                window.setTimeout("closeUserCreateAlert('status_update_"+form_id+"_"+role_id+"_"+workflow_id+"')", 3000);
                return false;
            }
            var data = {
                can_update : can_updates,
                role_id:role_id,
                form_id : form_id,
                workflow_id : workflow_ids,
                comment:$('#addcomment').val()
            }
            var url= "/settings/saveUpdateSetting/"+tracker_id;
            $.post(url, data,function(respJson){
                var resp =JSON.parse(respJson);
                var responseCode = resp.responseCode;
                var errMessage = resp.errMessage;
                if(responseCode == 1){
                    $("#addcommentasreason").modal('toggle');
                    $("#status_update_"+form_id+"_"+role_id+"_"+workflow_id).html('<font color="#088A08">'+errMessage+'</font>');
                    window.setTimeout("closeUserCreateAlert('status_update_"+form_id+"_"+role_id+"_"+workflow_id+"')", 3000);
                }
                else{
                    $("#status_update_").html('<font color="#cc0000">'+errMessage+'</font>');
                    window.setTimeout("closeUserCreateAlert('status_update_"+form_id+"_"+role_id+"_"+workflow_id+"')", 3000);
                }
            });
        }
    }
    function closeUserCreateAlert(id) {
        $("#"+id).html('');
    }

    function save_update_settings(form_ids,role_ids, workflow_ids)
    {
        var update=0;
        $("select[id^='id_can_update_"+form_ids+"_"+role_ids+"']").each(function () {
            var id=this.id;
            var can_update = $("#"+id).val();
            if( can_update == ""){
                update++;
            }
        });
        if( update > 0){
            $("#status_update_"+form_ids+"_"+role_ids+"_"+workflow_ids).html('<font color="red">Select Values</font>');
            window.setTimeout("closeUserCreateAlert('status_update_"+form_ids+"_"+role_ids+"_"+workflow_ids+"')", 3000);
            return false;
        } else {
            $('#addcommentasreason').modal('show');
            $('#commenterror').hide();
            $('#addcomment').val('');
            role_id=role_ids;
            form_id=form_ids; 
            workflow_id=workflow_ids;
            action_name='update';
        }
        window.setTimeout("closeUserCreateAlert('status_update_"+form_ids+"_"+role_ids+"_"+workflow_ids+"')", 5000);
    }


    function save_read_settings(form_ids,role_ids, workflow_ids)
    {
        var read=0;
        $("select[id^='id_can_read_"+form_ids+"_"+role_ids+"']").each(function () {
            var id=this.id;
            var can_read = $("#"+id).val();
            if( can_read == ""){
                read++;
            }
        });
        if( read > 0){
            $("#status_read_"+form_ids+"_"+role_ids+"_"+workflow_ids).html('<font color="red">Select Values</font>');
            window.setTimeout("closeUserCreateAlert('status_read_"+form_ids+"_"+role_ids+"_"+workflow_ids+"')", 3000);
            return false;
        } else {
            $('#addcommentasreason').modal('show');
            $('#commenterror').hide();
            $('#addcomment').val('');
            role_id=role_ids;
            form_id=form_ids; 
            workflow_id=workflow_ids;
            action_name='read';
        }
        window.setTimeout("closeUserCreateAlert('status_read_"+form_ids+"_"+role_ids+"_"+workflow_ids+"')", 5000);
    }
    function closeUserCreateAlert(id) {
        $("#"+id).html('');
    }
</script>


<style>
    th, td { white-space: nowrap; }

    div.dataTables_wrapper {
      width: 100%;
        margin: 0 auto;
    }


</style>