<?php
$trackerDetails = $trackerResults['tracker_details'];
$forms = $trackerResults['forms'];
$trackerName = $trackerDetails['name'];
$title = "$trackerName - Roles";
$this->headTitle($title);
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Settings</span></li>
        <li><span>Tracker Settings</span></li>
        <li class="active"><span>Role Management</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6 class="col-md-6 float-left">List of Roles</h6>
                <span class="col-md-6">
                   <button type="button" class="btn btn-primary float-right" onclick="window.location.href='/role/add/<?php echo $trackerId; ?>'">Add New Role</button>
                </span>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label class="col-sm-4"></label>
                    <div id="roleErrorMessages" class="error col-sm-6"></div>
                </div>
                <?php
                $flashMessage = $this->flashMessenger()->getMessages();
                if (count($flashMessage) && isset($flashMessage[0]['success'])) {
                    echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                }
                ?>
                <div class="table-responsive">
                     <table id="list_of_roles" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>Role</th>
                            </tr>
                        </thead>
                        <tbody id="clientbody">
                            
                            <?php foreach ($roles as $key => $values) { ?>
                                <tr>
                                    <td>
                                        <button type="button" onclick="window.location.href='/role/view/<?php echo $trackerId ?>/<?php echo $values['rid']; ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-eye" aria-hidden="true"></span>
                                        </button>
                                        <?php if (strtolower($values['role_name']) != 'administrator') { ?>
                                            <button type="button" onclick="window.location.href='/role/edit/<?php echo $trackerId ?>/<?php echo $values['rid']; ?>'" class="btn btn-default" aria-label="Left Align">
                                                <span class="lnr icon-pencil" aria-hidden="true"></span>
                                            </button>
                                            <button type="button" data-toggle="modal" data-target="#deleteRole_<?php echo $values['rid']; ?>" class="btn btn-default" aria-label="Left Align" onclick="reloadPopUp('<?php echo $values['rid']; ?>')">
                                                <span class="lnr icon-trash2" aria-hidden="true"></span>
                                            </button>
                                            <!-- Modal -->
                                            <div class="modal fade" id="deleteRole_<?php echo $values['rid']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteRoleModal" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="pb-1"><b>While removing this role it will delete from all assigned users also.</b></div>
                                                            <div class="form-group row">
                                                                <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                                                                <div class="col-sm-7">
                                                                    <textarea id="reason_<?php echo $values['rid']; ?>" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>   
                                                                    <span id="forReason_<?php echo $values['rid']; ?>" class="error"></span>
                                                                </div>
                                                            </div>
                                                            
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button id="reasonfordelete" onclick="deleteRoleAction('<?php echo $values['rid']; ?>', '<?php echo $trackerId; ?>')" type="button" class="btn btn-primary">Delete</button>
                                                            <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </td>
                                    <td><?php echo $values['role_name']; ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/module/common/role/role_management.js');
