<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();
$userContainer = $session->getSession('user');
$forms = isset($trackerResults['forms'])?$trackerResults['forms']:array();
$trackerDetails = isset($trackerResults['tracker_details'])?$trackerResults['tracker_details']:array();
$trackerName = isset($trackerDetails['name'])?$trackerDetails['name']."":"";
$iTrackerId = isset($forms[0]['tracker_id']) ? (int)$forms[0]['tracker_id'] : 0;
$iFormsId = isset($forms[0]['form_id']) ? (int)$forms[0]['form_id'] : 0;
$title = "$trackerName Product";
$this->headTitle($title);
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">        
        <li><span><a href="/dashboard/<?php echo $iTrackerId;?>/<?php echo $iFormsId;?>"><?php echo $trackerName;?></a></span></li>
        <li class="active"><span>Product Settings</span></li>        
        <li class="active"><span><a href='/product/<?php echo $iTrackerId ?>/<?php echo $iFormsId ?>'>Product Management</a></span></li>
        <li class="active"><span>Edit Product</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6 class="float-left">Edit Product</h6>
                <span class="float-right">
                    <button type="button" class="btn btn-primary" onclick="window.location.href='/product/add/<?php echo $trackerId ?>/<?php echo $iFormsId; ?>'">Add Product</button>
                </span>                
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label class="col-sm-4"></label>
                    <div id="productErrorMessages" class="error col-sm-6"></div>
                </div>
                <form id="productAddForm" method="post" name="myForm">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Product Name<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" value="<?php echo $name; ?>" id="product_name" name="product_name" required>
                            <div class="error" id="forProductName"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Product Code<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" value="<?php echo $code; ?>" placeholder="Product code" id="product_code" name="product_code" required>
                            <div class="error" id="forProductCode"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                           <textarea id="reason" class="form-control" placeholder="Reason for change" name="addcomment"></textarea>
                           <div id="forReason" class="error"></div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group row">
                            <?php if ($name != "") { ?>
                            <div class="offset-sm-4">
                                <button id ="savebtn" type="button" class="btn btn-primary ml-2" onclick="editProduct(<?php echo $trackerId; ?>,<?php echo $id; ?>,<?php echo $iFormsId; ?>)">Edit Product</button>
                                <button onclick="window.location.href='/product/<?php echo $trackerId ?>/<?php echo $iFormsId; ?>'" type="button" class="btn btn-default">Cancel</button>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php  $this->inlineScript()->appendFile($this->basePath() . '/js/module/sigtrace/product/listProduct.js', 'text/javascript');?>
