<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();
$userContainer = $session->getSession('user');
$form = isset($trackerResults['forms'])?$trackerResults['forms']:array();
$trackerDetails = isset($trackerResults['tracker_details'])?$trackerResults['tracker_details']:array();
$trackerName = isset($trackerDetails['name'])?$trackerDetails['name']."":"";
$trackerId = isset($form[0]['tracker_id']) ? (int)$form[0]['tracker_id'] : 0;
$formId = isset($form[0]['form_id']) ? (int)$form[0]['form_id'] : 0;
$title = "$trackerName Product";
$this->headTitle($title);
//print_r($trackerName);die;
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">        
        <li><span><a href="/dashboard/<?php echo $trackerId;?>/<?php echo $formId;?>"><?php echo $trackerName;?></a></span></li>
        <li><span>Product Settings</span></li>        
        <li class="active"><span>Product Management</span></li>
    </ol>
</div>
<div class="page-header"></div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6 class="col-md-6 float-left">List of Products</h6>
                <span class="col-md-6">
                   <button type="button" class="btn btn-primary float-right" onclick="window.location.href='/product/add/<?=$trackerId;?>/<?=$formId;?>'">Add New Product</button>                   
                </span>
            </div>
            <div class="card-body">
                <?php
                $flashMessage = $this->flashMessenger()->getMessages();
                if (count($flashMessage) && isset($flashMessage[0]['success'])) {
                    echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                }
                ?>
                <div class="form-group row">
                    <label class="col-sm-4"></label>
                    <div id="activeSubstanceErrorMessages" class="error col-sm-6"></div>
                </div>
                <div class="table-responsive">
                    <table id="list_of_substance" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>Product Name</th>
                                <th>Active Substance</th>
                                <th>Created Date</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($prodActSubList as $product){?>
                        <tr>
                            <td>
                                <button type="button" onclick="window.location.href='/product/edit/<?=$trackerId;?>/<?=$formId;?>/<?=$product['product_id']?>'" class="btn btn-default" title="Edit Producte" aria-label="Left Align">
                                            <span class="lnr icon-pencil" aria-hidden="true"></span>
                                </button>
                                <button type="button" data-toggle="modal"   class="btn btn-default" title="Delete Product" aria-label="Left Align" data-target="#deleteProduct_<?php echo $product['product_id']; ?>" onclick="reloadPopUp('<?php echo $product['product_id']; ?>')">
                                            <span class="lnr icon-trash2" aria-hidden="true"></span>
                                </button>
                                <div class="modal fade" id="deleteProduct_<?php echo $product['product_id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteProduct" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group row">
                                                            <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                                                            <div class="col-sm-7">
                                                                <textarea id="reason_<?php echo $product['product_id']; ?>" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>   
                                                                <span id="forReason_<?php echo $product['product_id']; ?>" class="error"></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button id="reasonfordelete" onclick="deleteProduct(<?php echo $product['product_id'];?>,<?php echo $trackerId; ?>, <?php echo $formId; ?>)" type="button" class="btn btn-primary">Delete</button>
                                                        <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                            </td>
                            <td><?=$product['product_name']?></td>
                            <td><?=$product['as_name']?></td>
                            <td><?=$product['product_created_date']?></td>
                            
                        </tr>
                    <?php } ?>
                    </tbody>
                    </table>
                </div>
            </div>      
        </div>
    </div>
</div>

<?php  $this->inlineScript()->appendFile($this->basePath() . '/js/module/sigtrace/product/listProduct.js', 'text/javascript');?>
<script>
<?php 
$msg = new \Zend\Session\Container('prd_msg');
if($msg->msg == 'ADD'){ ?>
   $('#alert').show().addClass('alert-success').html('<i class="icon-remove close" data-dismiss="alert"></i>Product added Successfully!!!'); 
<?php 
} else if($msg->msg == 'EDIT'){ ?>
     $('#alert').show().addClass('alert-success').html('<i class="icon-remove close" data-dismiss="alert"></i>Product edited Successfully!!!'); 
<?php 
} else if($msg->msg == 'DELETE'){ ?>
     $('#alert').show().addClass('alert-success').html('<i class="icon-remove close" data-dismiss="alert"></i>Product deleted Successfully!!!'); 
<?php 
}else{
?>
    $('#alert').hide().removeClass('alert-success').html('');
<?php    
} 
$msg->getManager()->getStorage()->clear('prd_msg');
?>
</script>