<?php 
$forms = $trackerResults['forms'];
$trackerDetails = $trackerResults['tracker_details'];
$trackerName = $trackerDetails['name'];
$title = "$trackerName - Calendar";
$this->headTitle($title);
$dateRange=date('d-M-Y',strtotime($eventData[0]['start_date'])).' / '.date('d-M-Y',strtotime($eventData[0]['end_date']));

?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
          <li><span><a href="/tracker/form/<?php echo isset($forms[0]['tracker_id'])?$forms[0]['tracker_id']:0;?>/<?php echo isset($forms[0]['form_id'])?$forms[0]['form_id']:0;?>"><?php echo $trackerName;?></a></span></li>
        <li><span><a href="/calendar/view/<?php echo $trackerId;?>/<?php echo isset($forms[0]['form_id'])?$forms[0]['form_id']:0;?>">View Calendar</a></span></li>
        <li class="active"><span><a href="/calendar/events_list/<?php echo $trackerId;?>/<?php echo isset($forms[0]['form_id'])?$forms[0]['form_id']:0;?>">Events List</a></span></li>
        <li class="active"><span>Edit Event</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
    <div class="card">
            <div  class="card-header"><h6>Edit Event</h6></div>
            <div class="card-body"> 
                <div class="error" id="editEventErrorMessages"></div>
                <div class="form-group row">
                    <label class="col-sm-4"></label>
                </div>
                <form autocomplete="off" id="eventAddForm" method="post" name="myForm">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Event Name<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <select type="text" class="form-control" placeholder="Select Event Name" id="e_name" name="e_name" required="true">
                                <option></option>
                                <?php foreach($events as $name) { ?> 
                                <option <?php echo (($eventData[0]['event_name'] == $name['event_name']) ? "selected" : '' );?> value="<?php echo $name['id'] ?>" ><?php echo $name['event_name'] ?></option>
                                <?php }?>
                            </select>
                            <div class="error" id="forEventName"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                     <label class="col-sm-4 col-form-label">Description<span class="error ml-1">*</span></label>
                     <div class="col-sm-6">
                        <input type="text" id="eventData" class="form-control" value="<?php echo $eventData[0]['event_data']?>" placeholder="Description" name="eventData">
                        <div id="forEventData" class="error"></div>
                     </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Select Start Date and End Date<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <div class="input-group date" data-provide="datepicker">
                                <input autocomplete="false" id="dateRange" name="daterange" type="text" value="<?php echo $dateRange ?>"placeholder="Select Date Range" class="form-control " >                                
                            </div>
                            <div class="error" id="forDateRange"></div>
                        </div>
                    </div> 
                    <div class="form-group row">
                     <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                     <div class="col-sm-6">
                        <textarea id="reason" class="form-control" placeholder="Reason for change" name="addcomment"></textarea>
                        <div id="forReason" class="error"></div>
                     </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group row">
                            <div class="offset-sm-4">
                                <button id ="savebtn" type="button" class="btn btn-primary ml-2" onclick="saveEditEvent(<?php echo $trackerId ?>,<?php echo $forms[0]['form_id']?>, <?php echo $eventId ?>)">Save</button>
                                <button onclick="window.location.href='/calendar/events_list/<?php echo $trackerId ?>/<?php echo isset($forms[0]['form_id'])?$forms[0]['form_id']:0;?>'" type="button" class="btn btn-default">Cancel</button>
                            </div>
                        </div>
                    </div>
                </form>                 
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/module/common/calendar/addEvent.js');
