
    <div class="container">
    <form class="form-signin" method="POST" style="background:white;border-radius: 20px;" role="form"  id="changepasswrd">
        <!--<input type="hidden" id="key" value="<?php //echo $key?>">-->
        <h2 class="form-signin-heading">Change Password</h2>
        <div class="inner-addon left-addon">
            <i class="glyphicon glyphicon-lock"></i>
            <input type="password" id="uopw"  style="padding-left: 28px;" name="upw" class="form-control" placeholder="Old Password" required>
        </div>
        </br>
        <div class="inner-addon left-addon">
            <i class="glyphicon glyphicon-lock"></i>
        <input type="password" id="unpw"  style="padding-left: 28px;" name="upw" class="form-control" placeholder="New Password" required>
        </div>
        </br>
        <div class="inner-addon left-addon">
            <i class="glyphicon glyphicon-lock"></i>
        <input type="password" id="ucpw"  style="padding-left: 28px;"  name ="cupw" class="form-control" placeholder="Confirm Password" required>
            </div>

        <span id="status"></span>
        <button class="btn btn-lg btn-primary btn-block" style="background-color:#343E59 ;" type="submit">Submit</button>
    </form>
        </div>




<!--/div-->


<script type="text/javascript">
    //var keys='<?php //echo $key?>';
    $(document).ready(function()
    {
        //$('.user').hide();
       // $('.sidebar').hide();
       // $('.topnav').hide();
        $("#uopw").val('');
        //            $('.navbar').hide();
        $("#changepasswrd").submit(function()
        {
            var oldpassword = $("#uopw").val();
            var newpassword = $("#unpw").val();
            var confirmpassword = $("#ucpw").val();
            var ccReg = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
            $("#status").html('');
            if(oldpassword.length ===0)
            {
                $("#status").html('<font color="#cc0000">Password Can not be blank</font>');
                return false;
            }
            else if(newpassword.length===0)
            {
                $("#status").html('<font color="#cc0000"> New Password can not be blank.</font>');
                return false;
            }
            else if(confirmpassword.length===0)
            {
                $("#status").html('<font color="#cc0000"> Confirm Password can not be blank.</font>');
                return false;
            }
            else if(confirmpassword!=newpassword){
            $("#status").html('<font color="#cc0000"> Password do not match.</font>');
            return false;
             }
            else if(newpassword.length < 8){
                $("#status").html('<font color="#cc0000"> Password atleast 8 charater long</font>');
                return false;
            }

            else if(!ccReg.test(newpassword)) {
                $("#status").html('<font color="#cc0000">Password must be 8 characters including 1 uppercase letter, 1 special character, alphanumeric characters.</font>');
                return false;
            }
            else
            {
              // $("#changepasswrd").submit();
                var data = {
                    oldpassword : oldpassword,
                    confirmpassword : confirmpassword,
                    newpassword:newpassword
                }
                var url = "/profile/changepassword";
                $.post(url, data,function(respJson){
                    if(respJson == 1){
                        $("#status").html('<font color="#cc0000">Password is changed.</font>');
                    }
                    else if(respJson == 2){
                        $("#status").html('<font color="#cc0000"> Old password is incorrect.</font>');
                    }
                });
                return false;
            }
            return false;
        });
    });
</script>


<style>
    /* enable absolute positioning */
    .inner-addon {
        position: relative;
    }

    /* style icon */
    .inner-addon .glyphicon {
        position: absolute;
        padding: 14px;
        pointer-events: none;
        z-index: 20;
    }

    /* align icon */
    .left-addon .glyphicon  { left:  0px;}
    .right-addon .glyphicon { right: 0px;}

    /* add padding  */
    .left-addon input  { padding-left:  30px; }
    .right-addon input { padding-right: 30px; }

    .form-signin {
        margin: 0 auto;
        max-width: 330px;
        padding: 15px;
    }
    .form-signin .form-signin-heading, .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        box-sizing: border-box;
        font-size: 16px;
        height: auto;
        padding: 10px;
        position: relative;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
        margin-bottom: -1px;
    }
    .form-signin input[type="password"] {
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        margin-bottom: 10px;
    }

</style>