
<div class="container">
    <div class="logo-expanded form-signin" style="font-size:30px;width: 400px;margin: 0 auto;">
        <i class="lnr icon-biobug"></i>
        <span class="nav-label logo-bio">BIOCLINICA</span>
        <span class="nav-label logo-product">PvTRACE</span>
    </div>
    <div class="clearfix"></div>
    <form class="form-signin" style="background:white;border: 1px solid #ccc;" role="form" action="logincheck" id="logincheck">
        <div class="form-group">
            <label for="reset-password">Email ID</label>
            <input type="username" id="u_name" id="inputEmail3" class="form-control" placeholder="Email">
        </div>
        <div id="status">&nbsp</div>
        <div class="form-group" style="margin-top:10px;">
                <button type="submit" class="btn btn-success">Reset</button>
                <button type="reset" class="btn btn-default">Clear</button>
                <div style="margin-top:10px;">
                    <a href="/">Back to Login</a>
                </div>
        </div>
        <div class="clearfix"></div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function()
    {
        $('.user').hide();
        $('.sidebar').hide();
        $('.topnav').hide();
        $("#upw").val('');
        //            $('.navbar').hide();
        $("#logincheck").submit(function()
        {
            var u_name = $("#u_name").val();
            if(u_name.length ===0)
            {
                $("#status").html('<font color="#cc0000">Email Can not be blank</font>');
            }
            else
            {
                $("#status").html('&nbsp;Processing in.');
                var data = {
                    u_name : u_name,
                }
                var url = "resetpassword";
                $.post(url, data).done(function(respJson){
                    if(respJson == 1){
                        $("#status").html('<font class="success">Mail has been sent to change the password.</font>');
                    }
                    else if(respJson == 'Not Acceptable'){
                        $("#status").html('<font class="error">Mail id does not exist.</font>');
                    }
                }).fail( function(xhr, textStatus, errorThrown) {
                    var err = xhr.responseText;
                    if(err == 1){
                        $("#status").html('<font class="success">Mail has been sent to change the password.</font>');
                    }
                    else if(err == 'Not Acceptable'){
                        $("#status").html('<font class="error">Mail id does not exist.</font>');
                    }
                    else if(err == 'Bioclinica user cannot reset password.'){
                        $("#status").html('<font class="error">Bioclinica user cannot reset password.</font>');
                    }
                });
            }
            return false;
        });
    });
</script>


<style>
    a, a:hover {
        color: #0080c4;
    }
    .form-signin {
        margin: 0 auto;
        max-width: 400px;
        padding: 15px;
    }
    .btn-success {
        background-color: #7AC143 !important;
        border: 1px solid #7AC143 !important;
    }
    .logo-expanded {
        font-size: 16px;
        font-weight: bold;
        /* text-transform: uppercase; */
        display: block;
        /*float: left;*/
        margin: 14px 50px 0 -2px;
    }
    .logo-expanded i {
        font-size: 26px;
        vertical-align: middle;
        margin-right: 5px;
        color: #73B72F;
    }
    .logo-expanded .nav-label {
        vertical-align: middle;
    }

    .logo-bio {
        color: #4E5860;
        border-right: 1px solid #ddd;
        padding-right: 7px;
    }
    .logo-product {
        color: #73B72F;
        padding-left: 2px;
    }
    .success{
        color: #7AC143;
    }

</style>