<?php
$title = 'Visualization Report'; 
$this->headTitle($title); 
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
      <li class="active"><span><?php echo $this->escapeHtml($title); ?></span></li>
    </ol>
</div>
<div class="card">
    <?php $kibanaDashboard= trim(base64_decode($kibana_url)); ?>
       <div  class="card-header">
            <button type="button" id="kibanalogin" class="btn btn-primary float-right" onclick="kibanapopUp('<?=$kibanaDashboard;?>')">Kibana Login</button>
     </div>
    <div class="card-body">
        <iframe id='dashboard' height="600" width="100%"></iframe>
     </div>
</div>
<script>
    var dashboardUrl= '<?php echo $kibanaDashboard?>';
    var popUpTime = '<?php echo $popUp_time?>';
</script>
        
    
<?php 
$this->inlineScript()->appendFile($this->basePath() . '/js/module/common/report/vreport.js');
?>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    