<?php 
    $title = 'Source List';
    $filterData = $_GET['filter'];
?>
<div class="pagebar container-fluid col-md-12">
    <ol class="breadcrumb">
        <li><span><a href="/dashboard/<?php echo $trackerId.'/'.$formId;?>">Dashboard</a></span></li>
        <li class="active"><span><?php echo $this->escapeHtml($title); ?></span></li>
    </ol>
</div>

<style>
.grid-container {
  display: grid;
  grid-column-gap: 3%;
  grid-row-gap: 10%;
  grid-template-columns: auto auto auto;
  padding: 10px;
}

</style>

<div class="card">
  <div class="card-body">
    <div class="card">
        
        

<div class="grid-container">
<?php foreach ($sourcelist as $key => $source) { ?>
                
                <div class="card btn-primary gridTab" formId="<?=$source["form_id"];?>" source="<?=$source["source_name"];?>" tabid="<?=$source["dashboard_id"];?>" asid="<?=$asId?>" filter="<?=$filterData?>">
                    <a href="javascript:void(0);" onclick="window.location.href = '#'">
                        <div class="card-body">
                            <h6 class="card-title text-white"><?php echo $source["source_name"]; ?></h6>
                                    <!-- <span class="float-left text-white"> Total : </span>
                                            <span class="float-right text-white">Pending : </span> -->
                        </div>
                    </a>
                </div>
            <?}?>
 
</div>
          
            
         
    </div>
  </div>
</div>




<script>
    var trackerId = '<?=$trackerId;?>';
    var formId = '<?=$formId;?>';
    var url = document.location.toString();
    $(function () {
        // if (url.match('#')) {
        //     $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
        // } else {
        //     $('#myTab li:first-child a').tab('show');
        // }
        $('#myTab li:first-child a').tab('show');
        //console.log($('#myTab li:first-child a'))
    });
    
</script>
<style>
    .ui-datepicker-today .ui-state-highlight { background: ...; }

</style>
<?php
$this->inlineScript()
    ->appendFile($this->basePath() . '/js/module/sigtrace/dashboard/dashboardTab.js');
