<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li class="active"><span>Page Not Found</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body"> 
        <div class="row">
            <div class="widget box">
                <div class="widget-content align-center">
                    <div class="alert alert-danger">
                        <b>Page Gone To Heaven And doesn't Want to Come Back.</b>
                        <div class="banner">
                            <img src="/assets/404_Error.png" alt="Page Not Found">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    b {
    color: #ea3c4d;
    font-family: "Condiment",cursive;
    font-size: 2.4em;
    font-weight: bold;
    margin-top: 20px;
    text-transform: capitalize;
}
</style>