<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li class="active"><span>Internal Server Error</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body"> 
        <div class="row">
            <div class="widget justify-content-center col-12">
                <div class="widget-content">
                    <div class="alert alert-danger">
                        <b style='font-size: 15.4em;'>500</b>
                        <h2>Internal Server Error</h2>
                        <h3>Our server isn't feeling too well</h3>
                        <h4>Come back later so you don't get sick to</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    b,h2,h3,h4 {
    color: #ea3c4d;
    font-family: "Condiment",cursive;
    font-size: 2.4em;
    font-weight: bold;
    margin-top: 20px;
    text-transform: capitalize;
}
</style>