<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();

$configContainer = $session->getSession('config');
$allowedFileSize=$configContainer->config['importFileSize'];
?>
<input type="hidden" id="auditlogmsg" value=""/>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><a href="/dashboard/<?=$trackerId;?>/<?=$formId;?>"><span>Dashboard</span></a></li>
        <li class="active"><span>Signal Calendar</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <?php
        $flashMessage = $this->flashMessenger()->getMessages();
        if (count($flashMessage) && isset($flashMessage[0]['success'])) {
            echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
        }
        ?>        
        <p class="alert-warning" id="alert"></p>
        <div class="error" id="errorcsv"></div>
        <div class="card">
            <div class="card-header">Import Signal Calendar File</div>
            <div id="part1">
            <form method='post' action='' enctype="multipart/form-data">
                <div class="modal-body">
                      <div class="input-group">
                        <div class="custom-file">
                          <input type="file" class="custom-file-input form-control" id="importCsvFile" aria-describedby="addon-wrapping" name="importCsvFile" accept=".csv,.xls,.xlsx">
                          <label class="custom-file-label" for="importCsvFile">Choose file</label>
                        </div>
                      </div>
                  <div class="error" id="ImportCsvFileMsg">
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" id="btnsigcalImport">Import</button>
                </div>
            </form>
            </div>
            


            


            <div class="card">
            <div class="card-header">Signal Calendar List</div>
          
            
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-0">Page Size:</div>
                    <div class="ml-2" style="width:80px!important;">
                        <select onchange="onPageSizeChanged()" id="page-size" class="form-control">
                            <option value="5" selected>5</option>
                            <option value="10">10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                            <option value="500">500</option>
                            <option value="1000">1000</option>
                        </select>
                    </div>
                    <div class="col-sm-2 ml-auto mb-2">
                        <div class="btn-toolbar">
                            <div class="btn-group toolbar-icons ml-auto" role="group">
                              <div class="btn-group" role="group">
                                  <button type="button" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="lnr icon-arrow-down-square"></i>
                                  </button>
                                  <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a class="dropdown-item" onclick="downloadCSV();">Export to CSV</a></li>
                                    <li><a class="dropdown-item" onclick="downloadEXCEL();">Export to Excel</a></li>
                                    <li><a class="dropdown-item" onclick="downloadPDF();">Export to PDF</a></li>
                                  </ul>
                              </div>
                              <!--<button type="button" class="btn btn-icon" id="dt_reload" onclick="refresh();"><i class="lnr icon-refresh"></i></button>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div id="myGrid" class="ag-theme-material"></div>
            </div>
        </div>
    </div>
</div>




<div id="validation_load" style="display:none">
    <p class="loader_img" id="loading_mask_loader">
    <img src="/assets/spinner.gif" alt="Loading..."  />
    <br/>
    <span>Validating File(s)...</span>
    </p>
</div>
<style> 
    #validation_load {
        width: 100%;
        height: 100%;
        top: 0;
        position: fixed;
        opacity: 0.7;
        background-color: #fff;
        z-index: 999999;
        left: 0px;
    }

#loading-image {
  position: absolute;
  top: 300px;
  /*left: 240px;*/
  z-index: 100;
}
</style>
<link href="/css/handsontable/handsontable.full.min.css" type="text/css" rel="stylesheet">
<script type="text/javascript">
    var trackerId="<?php echo $trackerId ?>";
    var formId="<?php echo $formId ?>";
    var allowedFileSize="<?php echo $allowedFileSize ?>";
</script>


<style> 
    .table{
        overflow-x: auto;
        max-width: 100%;
        display: block;
        white-space: nowrap;
    }
    .custom-tooltip {
        position: absolute;
        min-width: 150px;
        min-height: 70px;
        border: 1px solid cornflowerblue;
        overflow-x: auto;
        pointer-events: none;
        transition: opacity 1s;
    }
    .custom-tooltip.ag-tooltip-hiding {
        opacity: 0;
    }
    .custom-tooltip p {
        margin: 5px;
        white-space: nowrap;
    }
    .custom-tooltip p:first-of-type {
        font-weight: bold;
    }    
</style>
<script type="text/javascript">
    var trackerId="<?php echo $trackerId ?>";
    var formId="<?php echo $formId ?>";
    var productId="<?php echo $productId ?>";
    var dashboardId="<?php echo $dashboardId ?>"; 
    var filter="<?php echo $queryFilter ?>";
  
</script>


<?php 
    $this->inlineScript()
         // ->appendFile($this->basePath() . '/assets/bootstrap-filestyle/bootstrap-filestyle.min.js', 'text/javascript')
         ->appendFile($this->basePath() . '/js/module/sigtrace/import/casedata1.js', 'text/javascript')
         ->appendFile($this->basePath() . '/js/handsontable/handsontable.full.min.js', 'text/javascript')
         ->appendFile($this->basePath() . '/js/module/sigtrace/signalcalendar/signalcalendar.js', 'text/javascript');


