<!--    <h1>Greetings</h1>  
    ini template buat email !!  
    -->
    <table cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td style="padding:15px 15px 0 15px;background:#fff;border-radius:4px 4px 0 0">
                <div>
                    <img src="/images/Syn_logo.jpg" alt="image" height="85" width="290">
                </div>
            </td>
        </tr>
        <tr>
            <td style="padding:15px; background:#fff; border-radius:0 0 4px 4px;font-size:12px">
               Hello <br>
                Synowledge.<br><br>
                <div style="border-top:3px solid #eee;color:#999;font-size:11px;line-height:1.2">
                    <br>Powered by <a href="www.synowledge.com" target="_blank" style="color: #005399;text-decoration: none;">Synowledge</a>. All rights reserved.<br>
                </div>
            </td>
        </tr>
    </tbody>
</table>