<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();
$userContainer = $session->getSession('user');
$forms = isset($trackerResults['forms'])?$trackerResults['forms']:array();
$trackerDetails = isset($trackerResults['tracker_details'])?$trackerResults['tracker_details']:array();
$trackerName = isset($trackerDetails['name'])?$trackerDetails['name']."":"";
$trackerId = isset($forms[0]['tracker_id']) ? (int)$forms[0]['tracker_id'] : 0;
$formId = isset($forms[0]['form_id']) ? (int)$forms[0]['form_id'] : 0;
$title = "$trackerName Medical Concept";
$this->headTitle($title);
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span><a href="/dashboard/<?php echo $trackerId;?>/<?php echo $formId;?>"><?php echo $trackerName;?></a></span></li>
        <li><span><a href="/product/<?php echo $trackerId;?>/<?php echo $formId;?>">Product Settings</a></span></li>
        <li class="active"><span><a href="/activesubstance/activesubstance_management/<?php echo $trackerId;?>/<?php echo $formId;?>">Active Substance Management</a></span></li>
        <li class="active"><span>(Medical Concept/Preferred Term) Management</span></li>
    </ol>
</div>

<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6 class="col-md-6 float-left">List of Medical Concept/Preferred Term</h6>
                <span class="col-md-6">
                   <button type="button" class="btn btn-primary float-right" onclick="window.location.href='/medicalconcept/add/<?php echo $trackerId ?>/<?php echo $formId; ?>/<?php echo $activeSubstanceId ?>'">Add New Medical Concept/Preferred Term</button>
                </span>
            </div>
            <div class="card-body">
                <?php
                $flashMessage = $this->flashMessenger()->getMessages();
                if (count($flashMessage) && isset($flashMessage[0]['success'])) {
                    echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                }
                ?>
                <div class="table-responsive">
                    <table id="list_of_medical_concept" class="table table-striped">
                        <thead> 
                           <tr>
                                <th>Action</th>
                                <th>Medical Concept Name/Preferred Term</th>
                                <th>Type</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody id="clientbody">
                            <?php foreach ($medicalConceptData as $medicalConcept => $values) {  ?>
                                <tr>
                                    <td>
                                        <button type="button" onclick="window.location.href='/medicalconcept/edit/<?php echo $trackerId ?>/<?php echo $formId ?>/<?php echo $values['as_id'] ?>/<?php echo $values['pt_id'] ?>'" class="btn btn-default" title="Edit Medical Concept/Preferred Term" aria-label="Left Align">
                                            <span class="lnr icon-pencil" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" data-toggle="modal"  data-target="#deleteMedicalConcept_<?php echo $values['pt_id']; ?>" class="btn btn-default" title="Delete Medical Concept/Preferred Term" aria-label="Left Align" onclick="reloadPopUp('<?php echo $values['pt_id']; ?>')">
                                            <span class="lnr icon-trash2" aria-hidden="true"></span>
                                        </button>
                                        <!-- Modal -->
                                        <div class="modal fade" id="deleteMedicalConcept_<?php echo $values['pt_id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteMedicalConceptModal" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group row">
                                                            <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                                                            <div class="col-sm-7">
                                                                <textarea id="reason_<?php echo $values['pt_id']; ?>" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>   
                                                                <span id="forReason_<?php echo $values['pt_id']; ?>" class="error"></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button id="reasonfordelete" onclick="deleteMedicalConcept('<?php echo $values['pt_id']; ?>', '<?php echo $trackerId; ?>', '<?php echo $values['pt_name']; ?>', '<?php echo $formId; ?>', '<?php echo $activeSubstanceId ?>')" type="button" class="btn btn-primary">Delete</button>
                                                        <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td><?php echo $this->escapeHtml($values['pt_name']); ?></td>
                                    <td><?php echo $this->escapeHtml($values['pt_type']); ?></td>
                                    <td><?php if($values['pt_archive'] == 0) { echo "Active"; } else { echo "Deleted"; } ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>      
        </div>
    </div>
</div>
<div class="modal fade" id="self_delete" tabindex="-1" role="dialog" aria-labelledby="deleteMedicalConceptModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Warning!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<?php 
    $this->inlineScript()->appendFile($this->basePath() . '/js/module/sigtrace/product/listMedicalConcept.js', 'text/javascript');