<?php

$title = 'Trackers Management';
$this->headTitle($title);
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
      <li class="active"><span><?php echo $this->escapeHtml($title); ?></span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
         <div class="card">
             <div class="card-header">
                <h6 class="col-md-6 float-left">List of Trackers</h6>
                <span class="col-md-6">
                   <button type="button" class="btn btn-primary float-right" onclick="window.location.href='/tracker/add'">Add New Tracker</button>
                </span>   
             </div>
            <div class="card-body">
                <?php
                $flashMessage = $this->flashMessenger()->getMessages();
                if (count($flashMessage) && isset($flashMessage[0]['success'])) {
                    echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                }
                ?>
                
                <div class="table-responsive">
                    <table id="list_of_trackers" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>Tracker Name</th>
                                <th>Customer Name</th>
                            </tr>
                        </thead>
                        <tbody id="clientbody">
                            <?php foreach ($allclients as $client => $values) { ?>
                                <tr>
                                    <td>
                                        <button type="button" onclick="window.location.href='/tracker/view/<?php echo $values['tracker_id'] ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-eye" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" onclick="window.location.href='/tracker/edit/<?php echo $values['tracker_id'] ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-pencil" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" data-toggle="modal" data-target="#deleteTracker_<?php echo $values['tracker_id']; ?>" class="btn btn-default" aria-label="Left Align" onclick="reloadPopUp('<?php echo $values['tracker_id']; ?>')">
                                            <span class="lnr icon-trash2" aria-hidden="true"></span>
                                        </button>
                                        <!-- Modal -->
                                        <div class="modal fade" id="deleteTracker_<?php echo $values['tracker_id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteUserModal" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group row">
                                                            <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                                                            <div class="col-sm-7">
                                                                <textarea id="reason_<?php echo $values['tracker_id']; ?>" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>   
                                                                <span id="forReason_<?php echo $values['tracker_id']; ?>" class="error"></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button id="reasonfordelete" onclick="deleteTrackerAction('<?php echo $values['tracker_id']; ?>')" type="button" class="btn btn-primary">Delete</button>
                                                        <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td><?php echo $this->escapeHtml($values['tracker_name']); ?></td>
                                    <td><?php echo $this->escapeHtml($values['client_name']); ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/module/common/tracker/tracker.js');