<?php
$tracker_details = $trackerRsults['tracker_details'];
$forms = $trackerRsults['forms'];
//$table_details = $trackerRsults['table_details'];
$form_name = $form_details['form_name'];
$record = $form_details['record_name'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name Tracker - $form_name";
$this->headTitle($title);
//print_r($_SESSION['wfs']);
$sesswfs = $_SESSION['wfs'];
$keys_arr = array_keys($sesswfs);
$sess_key = $keys_arr[0];
$wf_details = $sesswfs[$sess_key];
$wf_name = $wf_details['wf_name'];
$wf_id = $wf_details['wf_id'];
//print_r($code_lists);
?>

<div class="container-liquid">
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <!--                <a class="closethis">Close</a>-->
                <header>
                    <h2 class="heading"><?php echo $this->escapeHtml($title); ?></h2>
                </header>
                <div class="contents boxpadding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'view', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><br/>Home</button>
                                </a>
                            </div>
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'settings', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><br/>Settings</button>
                                </a>
                            </div>
                            <?php
                            foreach ($forms as $key => $value) {
                                $form_name = $value['form_name'];
                                $form_id = $value['form_id'];
                                ?>

                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'form', 'tracker_id' => $tracker_id, 'action_id' => $form_id)) ?>">
                                        <button type="button" class="btn btn-<?php
                            if ($action_id == $form_id) {
                                echo 'info';
                            } else {
                                echo 'default';
                            }
                                ?>"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br/><?= $form_name; ?></button>
                                    </a>
                                </div>
                                <?
                            }
                            ?>
                            <div class="btn-group" style="float:right" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'newform', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span><br/>New Form</button>
                                </a>
                            </div>

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div  class="clearfix">
                                <?php $form_name = $form_details['form_name'];
                                ; ?>
                                <b>New Fields - <?= $wf_name; ?></b>
                            </div>
                            <hr/>
                            <form id="commentForm" method="post" action="" name="myForm" class="form-horizontal">
                                <table class="table table-striped" >
                                    <tr>

                                        <th>#Order</th>
                                        <th>Field Label name</th>
                                        <th>Field name</th>
                                        <th>Type</th>
                                        <th>KPI</th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    <tbody id="tabledivbody_fields">
                                        <?php
                                        $i = 0;
                                        foreach ($master_fields_array as $key => $value) {
                                            $master_field_id=isset($value['master_field_id']) ? $value['master_field_id'] : '';
                                            $label=isset($value['label']) ? $value['label'] : '';
                                            $field_type=isset($value['field_type']) ? $value['field_type'] : '';
                                            $field_name=isset($value['field_name']) ? $value['field_name'] : '';
                                            $kpi=isset($value['kpi']) ? $value['kpi'] : '';
                                            $m_code_list_id=isset($value['code_list_id']) ? $value['code_list_id'] : '';
                                            $i++;
                                            ?>
                                            <tr class="sectionsid">
                                                <td><span class="sort_order_td">#<?= $i; ?></span>
                                                    <input class="sort_rder" value="<?= $i; ?>" type="hidden"/>
                                                </td>
                                                <td>
                                                    <div class="form-group">
                                                        <input type="text" class="form-control quesiionIDs"  placeholder="Add Field" id="questionID_<?= $master_field_id; ?>" name="questionID_<?= $master_field_id; ?>" required value="<?= $label; ?>">
                                                        <input type="text" class="form-control expected" style="display:none" id="questionType_expected_<?= $master_field_id; ?>" value="<?= $m_code_list_id; ?>">
                                                        <input type="text" class="form-control roles" style="display:none" id="questionType_expected_<?= $master_field_id; ?>" value="">
                                                    </div>
                                                </td>
                                                <!-- S by Traz -->
                                                <td>
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" value="<?= $field_name; ?>" disabled>
                                                        <input type="hidden" class="form-control quesiionNames"  placeholder="Add Field" id="quesiionNames_<?= $master_field_id; ?>" name="quesiionNames_<?= $master_field_id; ?>" required value="<?= $field_name; ?>" >
                                                    </div>
                                                </td>
                                                <!-- E by Traz -->
                                                <td>
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" value="<?= $field_type; ?>" disabled>
                                                        <input type="hidden" class="form-control quesiionSelect"  placeholder="Add Field" id="questionType_<?= $master_field_id; ?>" name="questionType_<?= $master_field_id; ?>" required value="<?= $field_type; ?>" >
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="form-group">
                                                        <?php
                                                        if ($kpi == 0) {
                                                            $kpiVal = "None";
                                                        } else if ($kpi == 1) {
                                                            $kpiVal = "Critical";
                                                        } else if ($kpi == 2) {
                                                            $kpiVal = "Major";
                                                        } else if ($kpi == 3) {
                                                            $kpiVal = "Important";
                                                        }
                                                        ?>
                                                        <input type="text" class="form-control" value="<?= $kpiVal; ?>" disabled>
                                                        <input type="hidden" class="form-control quesiionKpi"  placeholder="Add Field" id="kpiType_<?= $master_field_id; ?>" name="kpiType_<?= $master_field_id; ?>" required value="<?= $kpi; ?>">
                                                    </div>
                                                </td>
                                                <td><span class="glyphicon glyphicon-arrow-down movecss"></span>
                                                    <span class="glyphicon glyphicon-arrow-up movecss"></span>
                                                </td>
                                                <td>
                                                    <i class="icon-remove" style="color: red; cursor: pointer;" onClick="delSuspectProduct(this)"></i>
                                                </td>
                                            </tr>
                                            <?
                                        }
                                        ?>
                                    </tbody>
                                </table>

                                <span id="status"></span><br/>
                                <button style="float:right" type="button"id="add_img" class="btn btn-primary" onClick="insSpec(); return false;" align="center">New Field</button>
                                <div style="clear:both"></div>
                                <div class="modal-footer">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'workflow', 'tracker_id' => $tracker_id, 'action_id' => $action_id)) ?>">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </a>
                                    <button onclick="addQusetions('next')" type="button" class="btn btn-primary">Save and Continue</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Row End -->
</div>
</div>
<!-- Content Section End -->
</div>
<!-- Right Section End -->
</div>
</div>
<div class="container-liquid">

    <!-- Row End -->
</div>
<input type="hidden" id="inputMaxFieldHidden" value="<?= $i; ?>">
<input type="hidden" id="input_hidden_codelist" value="<?= $i; ?>">
<input type="hidden" id="input_hidden_roles" value="<?= $i; ?>">
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script>

    $(document).ready(function() {
        var jsonData = <?php echo json_encode($code_lists); ?>
        var jsonString = JSON.stringify(jsonData);
        $('#input_hidden_codelist').val(jsonString);

        var jsonData = <?php echo json_encode($roles); ?>
        var jsonString = JSON.stringify(jsonData);
        $('#input_hidden_roles').val(jsonString);


        $("#tabledivbody_fields").sortable({
            items: "tr",
            cursor: 'move',
            opacity: 0.6,
            update: function() {
                sendOrderToServer();
            }
        });
        var jsonData = <?php echo json_encode(''); ?>
        var jsonString = JSON.stringify(jsonData);
        $('#inputWfHidden').val(jsonString);

        //            $('#commentForm').html(html);
    });

    function sendOrderToServer() {
        var elem = document.getElementsByClassName("sort_order_td");
        var max_sort_num = parseInt($('#inputMaxFieldHidden').val());
        for (var i = 0; i < elem.length; ++i) {
            elem[i].innerHTML = "#"+(1+i);
        }
        var elem = document.getElementsByClassName("sort_rder");
        for (var i = 0; i < elem.length; ++i) {
            elem[i].value = 1+i;
        }
    }

    function insSpec()
    {

        var str = random_string(6);
        var selid = 'questionID'+str
        var html = "";
        var maxfieldSortNumber = $('#inputMaxFieldHidden').val();
        maxfieldSortNumber = parseInt(maxfieldSortNumber);
        html += '<tr class="sectionsid">';
        html += '<td><span class="sort_order_td">#'+(maxfieldSortNumber+1)+'</span>';
        html += '<input class="sort_rder" value="'+(maxfieldSortNumber+1)+'" type="hidden"/>';
        html += '</td>';
        html += '<td>';
        html += '<div class="form-group">';
        html += '<input type="text" class="form-control quesiionIDs" onchange="validate_filed_name(this);" placeholder="Add Field Label" id="'+selid+'" name="questionID_'+selid+'" required>'
        html += '<input type="text" class="form-control expected111" style="display:none" id="questionType_'+selid+'_expected">'
        html += '</div>';

        html += '<div id="id_'+selid+'" style="display:none">';
        html += "<div class='form-group'>";
        html += '<label class="" style="padding-left: 10px;">Options</label>'
        html += '<select type="text" placeholder="Add Option" class="form-control expected" required id="id_'+selid+'_expected">';
        html += '<option value="0">None</option>';
        var respCheckListJson = $('#input_hidden_codelist').val();
        var resp_checklist =JSON.parse(respCheckListJson);
        var check_count = resp_checklist.length;
        for(var ck = 0; ck<check_count; ck++){
            var ck_list_id = resp_checklist[ck].code_list_id;
            var ck_list_name = resp_checklist[ck].code_list_name;
            html += '<option value="'+ck_list_id+'">'+ck_list_name+'</option>';
        }
        html += '</select>';
        html += '</div>';

        html += '</div>';


        html += '<div id="id_'+selid+'_role" style="display:none">';
        html += "<div class='form-group'>";
        html += '<label class="" style="padding-left: 10px;">Options</label>'
        html += '<select type="text" placeholder="Add Option" class="form-control roles" required id="id_'+selid+'_roles">';
        html += '<option value="0">None</option>';
        var respCheckListJson = $('#input_hidden_roles').val();
        var resp_checklist =JSON.parse(respCheckListJson);
        var check_count = resp_checklist.length;
        for(var ck = 0; ck<check_count; ck++){
            var ck_list_id = resp_checklist[ck].group_id;
            var ck_list_name = resp_checklist[ck].group_name;
            html += '<option value="'+ck_list_id+'">'+ck_list_name+'</option>';
        }
        html += '</select>';
        html += "</div>";
        html += '</div>';
        html += '</td>';
		// strats by traz
        html += '<td>';
		html += '<div class="form-group">';
        html += '<input type="text" class="form-control quesiionNames" onchange="validate_filed_name(this);" placeholder="Add Field Name"  name="quesiionNames_'+selid+'" required><span style="color:red;" id = "quesiionNames_'+selid+'" class = "error" ></span>'
		html += '</div>';
        html += '</td>';
		// ends by traz
        html += '<td>';
        html += '<div class="form-group">';
        html += '<select onchange="checkMultiple(\'id_'+selid+'\', this.id, 0, \'questionType_'+selid+'\')" type="text" class="form-control quesiionSelect" placeholder="Question type" id="questionType_'+str+'" name="questionStep_'+str+'" required>';
        html += '<option value="Integer">Integer</option>';
        html += '<option value="Text">Text</option>';
        html += '<option value="TextArea">Text Area</option>';
        html += '<option value="Date">Date</option>';
        html += '<option value="Date Time">Date Time</option>';
        html += '<option value="Check Box">Check Box</option>';
        html += '<option value="Combo Box">Combo Box</option>';
        html += '<option value="Formula">Formula</option>';
        html += '<option value="User">User</option>';
        html += '<option value="Heading">Heading</option>';
        html += '<option value="Formula Combo Box">Formula Combo Box</option>';
        html += '<option value="DependentText">DependentText</option>';
        html += '<option value="File">File</option>';
        html += '</select>';
        html += '</div>';
        html += '</td>';
        html += '<td>';
        html += '<div class="form-group">';
        html += '<select type="text" class="form-control quesiionKpi" placeholder="Question Kpi" id="kpiType_'+str+'" name="kpiType_'+str+'" required>';
        html += '<option value="0">None</option>';
        html += '<option value="1">Critical</option>';
        html += '<option value="2">Major</option>';
        html += '<option value="3">Important</option>';
        html += '</select>';
        html += '</div>';
        html += '</td>';
        html += '<td>';
        html += '<span class="glyphicon glyphicon-arrow-down movecss"></span>';
        html += '<span class="glyphicon glyphicon-arrow-up movecss"></span>';
        html += '</td>';
        html += '<td>';
        html += '<!--<i class="icon-arrow-up"></i><i class="icon-arrow-down"></i>--><i class="icon-remove" style="color: red; cursor: pointer;" onClick="delSuspectProduct(this)"></i>';
        html += '</td>';
        html += '</tr>';
        $("#tabledivbody_fields").append(html);
        sendOrderToServer();
    }
    // jquery starts by traz

    function make_field_name(data) {
            data = data.replace(/\W+/g, '');
            data = data.replace(/\s/g, '');
            data = data.toLowerCase();
            return data;
    }

    function validate_filed_name(type_flag) {

            var check = "questionID";
            var flag=true;

            $(".sectionsid").each(function(index,e){
                     var data = $.trim($(e).find('td input.quesiionIDs').val());
                     var name = "quesiionNames_"+type_flag.id;

                     if(data != ""){
                            if(type_flag == "") {
                                    data = $(e).find('td input.quesiionNames').val();
                            }
                            else {
                                    //if ($(e).find('td input.quesiionNames').val() == ""){
                                    if(type_flag.id.indexOf(check) != -1){
                                            data = make_field_name(data);
                                            $(e).find('td input[name="'+name+'"]').val(data);
                                            //$(e).find('td input.quesiionNames').val(data);
                                    }
                                    else{
                                            data = make_field_name($(e).find('td input.quesiionNames').val());
                                            $(e).find('td input[name="'+name+'"]').val(data);
                                    }
                            }

                            if(data.length > 30){
                                    $(e).find('td span#'+name+'').html('Option name can\'t be more than 30 caharacters! ');
                                    //$(e).find('td span.error').html('Option name can\'t be more than 30 caharacters! ');

                                    flag=false;
                            }
                            else {
                                $(e).find('td span.error').html('');
                                return true;
                            }

                     }
                     else {
                            $(e).find('td input[name="'+name+'"]').val("");
                            $(e).find('td span.error').html('');
                            return true;
                    }


            });
            return flag;
    }
    // jquery ends by traz


    function checkMultiple(id, selID, start, questionType){

        var selVal= $('#'+selID).val();
        var html="";
        var str = random_string(6);
        var respCheckListJson = $('#input_hidden_codelist').val();
        var resp_checklist =JSON.parse(respCheckListJson);
        $("#"+id+"_expected").val(0);

        if(selVal == 'Check Box' || selVal == 'Combo Box' || selVal=='Formula Combo Box'){
            $("#"+id).show();
            $("#"+id+"_role").hide();
            $("#"+id+"_roles").val("0");
        }
        else if(selVal == 'User'){
            var respCheckListJson = $('#input_hidden_roles').val();
            var resp_checklist =JSON.parse(respCheckListJson);
            $("#"+id+"_role").show();
            $("#"+id).hide();
             $("#"+id+"_expected").val("0");
            //    $("#"+id).show();
        }
        else{
            $("#"+id+"_expected").val("0");
            $("#"+id+"_roles").val("0");
            $("#"+id).hide();
            $("#"+id+"_role").hide();

        }
    }

function random_string(size){
    var str = "";
    for (var i = 0; i < size; i++){
        str += random_character();
    }
    return str;
}

function random_character() {
    var chars = "lmnopqurstuvwxyzABCDEFGHIJKLMNOPQURSTUVWXYZ";
    return chars.substr( Math.floor(Math.random() * 62), 1);
}
function delSuspectProduct(node)
{
    r = node.parentNode.parentNode;
    r.parentNode.removeChild(r);
    sendOrderToServer();
}

function addQusetions()
{
   var type_flag = "";
  if (validate_filed_name(type_flag)) {

    var elem = document.getElementsByClassName("quesiionIDs");
    var names = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            names.push(elem[i].value);
        }
    }
    // S by Traz
    var elem = document.getElementsByClassName("quesiionNames");
    var label_names = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            label_names.push(elem[i].value);
        }
    }
    // E By Traz
    var elem = document.getElementsByClassName("quesiionSelect");
    var types = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            types.push(elem[i].value);
        }
    }

    var elem = document.getElementsByClassName("expected");
    var expected = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            expected.push(elem[i].value);
        }
    }

    var elem = document.getElementsByClassName("quesiionKpi");
    var kpivalues = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            kpivalues.push(elem[i].value);
        }
    }
    var elem = document.getElementsByClassName("sort_rder");
    var field_sort_order = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            field_sort_order.push(elem[i].value);
        }
    }

    var elem = document.getElementsByClassName("roles");
    var roles = [];
    for (var i = 0; i < elem.length; ++i) {
        if (typeof elem[i].value !== "undefined") {
            roles.push(elem[i].value);
        }
    }

    var $valid = $("#commentForm").valid();
    if(!$valid) {
        return false;
    }else{
        $("#status").html('processing...');
        var tracker_id = '<?= $tracker_id; ?>';
        var action_id = '<?= $action_id; ?>';
        var wf_id = '<?= $wf_id; ?>';

        var data = {
            names : names,
            label_names : label_names,
            types : types,
            expected : expected,
            action_id: action_id,
            kpivalues:kpivalues,
            tracker_id : tracker_id,
            workflow_id : wf_id,
            field_sort_order : field_sort_order,
            subType : 'next',
            sess_key : '<?= $sess_key; ?>',
            formula_id : roles
        }
        var url = "<?php echo $this->url('tracker', array('action' => 'savenewfields')); ?>";
        $.post(url, data,function(respJson){
            var resp =JSON.parse(respJson);
            var responseCode = resp.responseCode;
            var errMessage = resp.errMessage;
            if(responseCode == 1){
                $("#status").html('<font color="#088A08">'+errMessage+'</font>');
                window.setTimeout('window.location.replace("<?php echo $this->url('tracker', array('action' => 'addfields', 'tracker_id' => $tracker_id, 'action_id' => $action_id)) ?>")', 1000);
            }
            else{
                $("#status").html('<font color="#cc0000">'+errMessage+'</font>');
            }
        });
    }
  }
  else {
	  return false;
  }
}
</script>
