<?php
$tracker_details = $trackerRsults['tracker_details'];
$forms = $trackerRsults['forms'];
//$table_details = $trackerRsults['table_details'];
$form_name = $form_details['form_name'];
$record = $form_details['record_name'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name Tracker - $form_name";
$this->headTitle($title);
unset($_SESSION['wfs']);
?>

<div class="container-liquid">
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <!--                <a class="closethis">Close</a>-->
                <header>
                    <h2 class="heading"><?php echo $this->escapeHtml($title); ?></h2>
                </header>
                <div class="contents boxpadding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'view', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><br/>Home</button>
                                </a>
                            </div>
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'settings', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><br/>Settings</button>
                                </a>
                            </div>
                            <?php
                            foreach ($forms as $key => $value) {
                                $form_name = $value['form_name'];
                                $form_id = $value['form_id'];
                                ?>

                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'form', 'tracker_id' => $tracker_id, 'action_id' => $form_id)) ?>">
                                        <button type="button" class="btn btn-<?php
                            if ($action_id == $form_id) {
                                echo 'info';
                            } else {
                                echo 'default';
                            }
                                ?>"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br/><?= $form_name; ?></button>
                                    </a>
                                </div>
                                <?
                            }
                            ?>
                            <div class="btn-group" style="float:right" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'newform', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span><br/>New Form</button>
                                </a>
                            </div>

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div  class="clearfix">
                                <?php $form_name = $form_details['form_name'];
                                ; ?>
                                <b>New Workflow - <?= $form_name; ?></b>
                            </div>    
                            <hr/>
                            <form id="commentForm" method="post" action="" name="myForm" class="form-horizontal">
                                <table class="table table-striped" id="">
                                    <tr>
                                        <th>#Order</th>
                                        <th>Workflow Name</th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                               
                                    <tbody id="tabledivbody" >
                                        <tr class="sectionsid">
                                            <td><span class="sort_order_td">#<?=$max_sort_number+1;?></span>
                                            <input class="sort_rder" value="<?=$max_sort_number+1;?>" type="hidden"/>
                                        </td>
                                        <td>
                                            <input list="questionType" name="questionStep" class="form-control quesiionSelect" required/>
                                            <datalist placeholder="Workflow name" id="questionType" required>
                                                <?php
                                                $m_wf_arr = array();
                                                foreach ($master_workflow_array as $key => $value) {
                                                    $mast_wf_name = $value['workflow_name'];
                                                    $m_wf_arr[] = $mast_wf_name;
                                                    ?>
                                                    <option value="<?= $mast_wf_name ?>"><?= $mast_wf_name ?></option>
                                                    <?
                                                }
                                                ?>
                                            </datalist>
                                            <span id="error_0" class="errorworkflow" style="display:none"></span>
                                        </td>
                                        <td><span class="glyphicon glyphicon-arrow-down"></span>
                                            <span class="glyphicon glyphicon-arrow-up"></span>
                                        </td>
                                        <td></td>
                                        </tr>

                                        </tbody>
                                </table>                                


                                <span id="status"></span><br/>
                                <button style="float:right" type="button"id="add_img" class="btn btn-primary" onClick="insSpec(); return false;" align="center"> +Workflow</button>
                                <div style="clear:both"></div>
                                <div class="modal-footer">
<!--                                    <button onclick="addQusetions('save')" type="button" class="btn btn-primary">Save</button>-->
                                    <a href="<?php echo $this->url('tracker', array('action' => 'workflow', 'tracker_id' => $tracker_id, 'action_id' => $action_id)) ?>">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </a>
                                    <button onclick="addQusetions('next')" type="button" class="btn btn-primary">Save And Continue</button>
                                </div>
                            </form>

                           

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Row End -->
</div>
</div>
<!-- Content Section End -->
</div>
<!-- Right Section End -->
</div>
</div>
<div class="container-liquid">

    <!-- Row End -->
</div>
<input type="hidden" id="inputWfHidden">
<input type="hidden" id="inputMaxWfHidden" value="<?=$max_sort_number;?>">
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script>
    $(document).ready(function() {
        var jsonData = <?php echo json_encode($m_wf_arr); ?> 
        var jsonString = JSON.stringify(jsonData);
        count=1;
        $('#inputWfHidden').val(jsonString);
        
        
        $("#tabledivbody").sortable({
            items: "tr",
            cursor: 'move',
            opacity: 0.6,
            update: function() {
                sendOrderToServer();
            }
        });
    });	

    function sendOrderToServer() {
        var elem = document.getElementsByClassName("sort_order_td");
        var max_sort_num = parseInt($('#inputMaxWfHidden').val());
        for (var i = 0; i < elem.length; ++i) {
            elem[i].innerHTML = "#"+(max_sort_num+1+i);
        }
        var elem = document.getElementsByClassName("sort_rder");
        
        for (var i = 0; i < elem.length; ++i) {
                elem[i].value = max_sort_num+1+i;
        }
    }
    function insSpec()
    {
        var jsonString = $('#inputWfHidden').val();
        var wf_arr =JSON.parse(jsonString);
        var str = random_string(6);
        var selid = 'questionID'+str
        var html = "";
        html += '<tr class="sectionsid">';
        html += '<td><span class="sort_order_td">#1</span><input class="sort_rder" value="" type="hidden"/></td>';
        html += '<td>';
        html += '<input list="questionType_'+selid+'" name="questionStep_'+selid+'" class="form-control quesiionSelect" required/>'
        html += '<datalist placeholder="Workflow name" id="questionType_'+selid+'">'
        var countWf = wf_arr.length;
        for(var m=0; m<countWf; m++){
            var wf_name = wf_arr[m];
            html += '<option value="'+wf_name+'">'+wf_name+'</option>'
        }
        html += '</datalist>'
        html +='<span id="error_'+count+'"  style="display:none" class="errorworkflow"></span>'
        count++;
        html += '</td>'
        html += '<td>';
        html += '<span class="glyphicon glyphicon-arrow-down"></span>';
        html += '<span class="glyphicon glyphicon-arrow-up"></span>';
        html += '</td>';
        html += '<td>'
        html+= '<!--<i class="icon-arrow-up"></i><i class="icon-arrow-down"></i>--><i class="icon-remove" style="color: red; cursor: pointer;" onClick="delSuspectProduct(this)"></i>';
        html += '</td>'
        $("#tabledivbody").append(html);
        sendOrderToServer();
    }
    function random_string(size){
        var str = "";
        for (var i = 0; i < size; i++){
            str += random_character();
        }
        return str;
    }
    
    function random_character() {
        var chars = "lmnopqurstuvwxyzABCDEFGHIJKLMNOPQURSTUVWXYZ";
        return chars.substr( Math.floor(Math.random() * 62), 1);
    }
    function delSuspectProduct(node)
    {
        r = node.parentNode.parentNode;
        r.parentNode.removeChild(r);
        sendOrderToServer();
    }

    function addQusetions(subType)
    {
        $("#status").html('');
        $(".errorworkflow").html('');
        var elem = document.getElementsByClassName("quesiionSelect");
        var wf_names = [];
        for (var i = 0; i < elem.length; ++i) {
            if (typeof elem[i].value !== "undefined") {
                var workflow_name=elem[i].value.trim();
                if (wf_names.indexOf(workflow_name) == -1) {
                    wf_names.push(workflow_name);
                }else{
                    $("#status").html('<font color="#cc0000">Duplicate Workflow Name</font>');
                    return false;
                }
            }
        }
        var elem = document.getElementsByClassName("sort_rder");
        var wf_sort_order = [];
        for (var i = 0; i < elem.length; ++i) {
             if (typeof elem[i].value !== "undefined") {
                wf_sort_order.push(elem[i].value);
            }
        }
        
        var error_index = document.getElementsByClassName("errorworkflow");
        var index_of_error = [];
        for (var i = 0; i < error_index.length; ++i) {
                index_of_error.push(error_index[i].id);
        }
        var $valid = $("#commentForm").valid();
        if(!$valid) {
            return false;
        }else{
            $("#status").html('processing...');
            var action_id = '<?= $action_id; ?>';
            var tracker_id = '<?= $tracker_id; ?>';
            var data = {
                wf_names : wf_names,
                index_of_error:index_of_error,
                action_id: action_id,
                tracker_id: tracker_id,
                subType : subType,
                wf_sort_order : wf_sort_order
            }
            var url = "<?php echo $this->url('tracker', array('action' => 'saveworkflow','tracker_id'=>$tracker_id,'action_id'=>$action_id)); ?>";
            $.post(url, data,function(respJson){
                var resp =JSON.parse(respJson);
                $("#status").html('');
                var responseCode = resp.responseCode;
                var errMessage = resp.errMessage;
                if(responseCode == 1){
                    $("#status").html('<font color="#088A08">'+errMessage+'</font>');
                    if(subType =='save'){
                        window.setTimeout('window.location.replace("<?php echo $this->url('tracker', array('action' => 'workflow', 'tracker_id' => $tracker_id, 'action_id' => $action_id)) ?>")', 1000);
                    }else{
                        window.setTimeout('window.location.replace("<?php echo $this->url('tracker', array('action' => 'workflow', 'tracker_id' => $tracker_id, 'action_id' => $action_id)) ?>")', 1000);
                    }
                }
                else if(responseCode == 2){
                    $.each(errMessage, function(idx, obj){ 
                        $("#"+idx).show();
                        $("#"+idx).html('<font color="#cc0000">'+obj+'</font>');
                    });
                }  
                else{
                    $("#status").html('<font color="#cc0000">'+errMessage+'</font>');
                }
            });
        }
    }
</script>
