<?php
$tracker_details = $trackerRsults['tracker_details'];
$forms = $trackerRsults['forms'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name - Default Report Settings";
$this->headTitle($title);


$wfs = $resultset[0];
$roles = $resultset[1];
$default_report=$resultset[2];
//print_r($default_report);die;
$i=0;

foreach ($wfs as $value_wf) {
        $reportarray[$i]['form_id']=$value_wf->form_id;
        $reportarray[$i]['report_id']=$value_wf->report_id;
        $reportarray[$i]['report_name']=$value_wf->report_name;
      //  $reportarray[$i]['default_report_id']=$value_wf->default_report_id;
        $i++;
}

//print_r($reportarray);die;
?>


<div class="container-liquid">
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <!--                <a class="closethis">Close</a>-->
                <header>
                    <h2 class="heading"><?php echo $this->escapeHtml($title); ?></h2>
                </header>
                <div class="contents boxpadding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'view', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><br/>Home</button>
                                </a>
                            </div>
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'settings', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><br/>Settings</button>
                                </a>
                            </div>
                            <?php
                            foreach ($forms as $key => $value) {
                                $form_name = $value['form_name'];
                                $form_id = $value['form_id'];
                                ?>

                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'form', 'tracker_id' => $tracker_id, 'action_id' => $form_id)) ?>">
                                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br/><?= $form_name; ?></button>
                                    </a>
                                </div>
                                <?
                            }
                            ?>
                            <div class="btn-group" style="float:right" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'newform', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span><br/>New Form</button>
                                </a>
                            </div>

                        </div>
                    </div>
                    <div class="panel panel-default" >
                        <div class="panel-body">
                            <div  class="clearfix">
                                <b>Default Report Settings</b>
                            </div>
                            <hr/>
                            <?
                            $id = 1;
                            $form_name='';
                            $form_id=0;
                            foreach ($wfs as $value_wf) {

                               $option='';
                            if ($form_id != $value_wf->form_id){
                                $form_id = $value_wf->form_id;
                            ?>
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <?
                                    $form_name = $value_wf->form_name;
                                    echo "<h4>Form - $form_name</h4><hr/>";
                                    ?>

                                    <table class="table table-striped" id="accessreport_<?php echo $id ?>" >
                                        <thead>
                                        <tr>
                                            <th>Group Name</th>
                                            <th>Select Report</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody id="recordsbody">

                                        <?
                                        if (array_key_exists(0, $roles)) {
                                            foreach ($roles as $key_role_arr => $value_role_arr) {
                                                $option = '';
                                                $role_id = $value_role_arr->group_id;
                                                $ids=array();
                                                $option .= '<option value="">Select Report</option>';
                                                        foreach ($reportarray as $reports) {
                                                            if ($form_id == $reports['form_id']) {
                                                                // $selected='';
                                                                foreach ($default_report as $defaultreports) {
                                                                    // print_r($defaultreports);die;
                                                                    if ($defaultreports->form_id == $form_id && $role_id == $defaultreports->role_id && $reports['report_id'] == $defaultreports->report_id) {
                                                                        $selected = 'selected';
                                                                        break;

                                                                    } else {
                                                                        $selected = '';
                                                                    }

                                                                }


                                                                    if (!in_array($reports['report_id'], $ids)) {
                                                                        $option .= '<option ' . $selected . ' value=' . $reports['report_id'] . '>' . $reports['report_name'] . '</option>';
                                                                        $ids[] = $reports['report_id'];
                                                                    }

                                                            }
                                                        }

                                                /*}
                                                else{
                                                    foreach ($reportarray as $reports) {
                                                        if ($form_id == $reports['form_id']) {
                                                            $option .= '<option ' . $selected . ' value=' . $reports['report_id'] . '>' . $reports['report_name'] . '</option>';
                                                        }
                                                    }

                                                }*/
                                                $group_name = $value_role_arr->group_name;
                                                $group_archived = $value_role_arr->group_archived;
                                                if ($group_archived == 0) {


                                                    ?>
                                                    <tr>
                                                        <td><?= $group_name ?></td>
                                                        <td>
                                                            <?php  if ($group_name == "Administrator" || $group_name == "SuperAdmin") {?>
                                                                Full Access
                                                        <?php } else {?>
                                                            <select id="id_<?= $role_id ?>_<?= $form_id ?>">
                                                                <?php echo $option ?>
                                                            </select>
                                                        <?php } ?>

                                                        <td>
                                                            <?
                                                            if ($group_name != "Administrator" || $group_name == "SuperAdmin") {
                                                                ?>
                                                                <div id="status_<?= $role_id ?>_<?= $form_id; ?>"></div>
                                                                <button
                                                                    onclick="save_report_settings('<?= $role_id ?>','<?= $form_id ?>')"
                                                                    type="button" class="btn btn-primary">Save
                                                                </button>
                                                            <? } ?>
                                                        </td>
                                                    </tr>
                                                    <?
                                                }
                                            }
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                                <?php
                                ?>
                                <?
                                $id++;
                                }



                            }

                    ?>

            </div>
        </div>

    </div>
</div>
</div>
 </div>
<!-- Row End -->
</div>
</div>
 <div class="modal fade" id="addcommentasreason" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                  <div>      
        <br />
        <br />
    </div>   <div class="modal-dialog"  style="margin-bottom:0px;" >
                                        <div class="modal-content" id="modelContentAdd">

                                            <div class="panel-primary" style="margin:0px">
                                                <div class="panel-heading">Comments<button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button></div>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <textarea id="addcomment" class="form-control" placeholder="Add Comment" name="addcomment"></textarea>   
                                                    <span id="commenterror" style="display:none;color: red;">Please add reason for change</span>
                                                    <span id="status_for_reason"></span>
                                                </div>
                                            </div>
                                            </div>

                                            <div style="clear:both"></div>
                                            
                                            <div class="modal-footer">
                                               <button onclick="reasonforchange()" type="button" class="btn btn-primary">Save</button>
                                                <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
    </div>
<!-- Content Section End -->
</div>
<!-- Right Section End -->
</div>
</div>

<div class="container-liquid">

    <!-- Row End -->
</div>

<script>

    $(document).ready(function() {
        $("table[id^='accessreport_']").each(function () {
            var id=this.id;
            var table_read=$("#"+id).dataTable( {
                "bDestroy": true,
                "scrollY":   800,
                "scrollX":   true,
                "bPaginate": false,
                "bInfo" : false,
                "bFilter": false,
                "scrollCollapse": true,
                fixedColumns: {
                    leftColumns: 1
                }
                // "bAutoWidth": false
            });
//            new $.fn.dataTable.FixedColumns( table_read, {
//             leftColumns: 1
//
//             });
        });
    });
    function closeUserCreateAlert(id) {
        $("#"+id).html('');
    }



    function save_report_settings(role_ids,form_ids)
    {
		 $('#addcommentasreason').modal('show');
        $('#commenterror').hide();
        $('#addcomment').val('');
        role_id=role_ids;
        form_id=form_ids;
	}
	function reasonforchange(){
		var tracker_id="<?php echo $tracker_id  ?>";
        if ($('#addcomment').val() == ''){
            $('#commenterror').show();
            return false;
        }
        $('#commenterror').hide();
        var access='';
        var workflow_ids = [];
        var can_accessarry=[];
        $("select[id^='id_"+role_id+"_"+form_id+"']").each(function () {
            var res=(this.id).split('_');
            var id=this.id;
            var can_access = $("#"+id).val();
            if( can_access != ""){
                access=can_access;
            }
            can_accessarry.push(can_access);

        });
        $("#status_"+role_id+"_"+form_id).html('processing...');
        if( access == ""){
            $("#status_"+role_id+"_"+form_id).html('<font color="red">Select Values</font>');
            window.setTimeout("closeUserCreateAlert('status_"+role_id+"_"+form_id+"')", 3000);
            return false;
        }
        var data = {
            can_access : can_accessarry,
            role_id:role_id,
            form_id : form_id,
            comment:$('#addcomment').val()
        }
        var url = "<?php echo $this->url('tracker', array('action' => 'savedefaultreportsetting')); ?>";
        $.post(url, data,function(respJson){ 
            var resp =JSON.parse(respJson);
            var responseCode = resp.responseCode;
            var errMessage = resp.errMessage;
            if(responseCode == 1){
                $("#status_"+role_id+"_"+role_id).html('<font color="#088A08">'+errMessage+'</font>');
                window.setTimeout("closeUserCreateAlert('status_"+role_id+"_"+form_id+"')", 3000);
                 $("#status_"+role_id+"_"+form_id).html('Success').css({"color":"green"});
            }
            else{
                $("#status_"+role_id+"_"+role_id).html('<font color="#cc0000">'+errMessage+'</font>');
                window.setTimeout("closeUserCreateAlert('status_"+role_id+"_"+form_id+"')", 3000);
            }            
            $('#addcommentasreason').modal('hide');
        });
        
    }




</script>


<style>
    th, td { white-space: nowrap; }

    div.dataTables_wrapper {
      /*width: 785px;*/
        margin: 0 auto;
    }


</style>