<div class="card">
  <div id="alertWorkflow"></div>
  <div class="card-body">

    <form id ="workflowForm" enctype='multipart/form-data' class='workflowFormClass'>
        <div class="form-group row" id="fieldsDiv">
        </div>

        <div class="form-group">
            <div class="row float-right" id="submitResetCancelButton">
              <div class="mx-auto" style="width: 80px;">
                <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
              </div>
              <div class="mx-auto" style="width: 80px;">
                <button type="reset" class="btn btn-danger" >Reset</button>
              </div>
              <div class="mx-auto" style="width: 80px;">
                <a href="<?php echo $this->url('tracker',array('action' => 'form', 'tracker_id' => $tracker_id,'action_id' => $action_id)) ?>" id="cancel" name="cancel" class="btn btn-default">Cancel</a>
              </div>
            </div>
        </div>
        
    </form>

  </div>
</div>