<?php
//echo $date_format_selected;die;
use Zend\Session\Container;
$tracker_details = $trackerRsults['tracker_details'];
$forms = $trackerRsults['forms'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name- Date Settings";
$this->headTitle($title);
$container = new Container('msg');
//echo $container->messg;die;
?>


<div class="container-liquid">
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
<!--                                <a class="closethis">Close</a>-->
                <header>
                    <h2 class="heading"><?php echo $this->escapeHtml($title); ?></h2>
                </header>
                <div class="contents boxpadding">
                   
                </div>
                <div class="contents boxpadding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'view', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><br/>Home</button>
                                </a>
                            </div>
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'settings', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><br/>Settings</button>
                                </a>
                            </div>
                            <?php
                            foreach ($forms as $key => $value) {
                                $form_name = $value['form_name'];
                                $form_id = $value['form_id'];
                                ?>

                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'form', 'tracker_id' => $tracker_id, 'action_id' => $form_id)) ?>">
                                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br/><?= $form_name; ?></button>
                                    </a>
                                </div>
                                <?
                            }
                            ?>
                            <div class="btn-group" style="float:right" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'newform', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span><br/>New Form</button>
                                </a>
                            </div>

                        </div>
                    </div>
                    
                    
                    
                    
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div  class="clearfix">
                            </div>
                            <hr/>

                            <form id="trackerdatesetting" method="post" action="/tracker/tracker_date_setting/<?php echo $tracker_id ?>" name="myForm" class="form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label" style="padding-left: 0px;">Date Format</label>
                                    <div class="col-sm-3">
                                        <select type="text" class="form-control quesiionMandatory-edit" placeholder="MandatoryType" id="date_format" name="date_format" value="Select Date Format" required>
                                        <option value="">Select Date Format</option>
                                         <?php 
                                        // $dformat = $selected['']
                                        foreach($date_format as $value_cl){
                                            $date_format_id = $value_cl['id'];
                                            $date_format_name = $value_cl['date_format'];
                                            $php_date_format_name = $value_cl['php_date_format'];
                                            $jquery_date_format_name = $value_cl['jquery_date_format'];
                                            $pregmatch_date_name=$value_cl['pregmatch_date'];
                                            
                                            ?>
                                                <option <?php  echo ($date_format_selected == $php_date_format_name)? "selected='selected'":"" ?> value="<?=$date_format_name."@".$php_date_format_name."@".$jquery_date_format_name."@".$pregmatch_date_name;?>"><?=date($php_date_format_name);?></option>
                                            <?php
//                                            echo "<pre>";
//                                            print_r($value_cl);
//                                            echo "</pre>";
                                        }
                                        ?>
                                    </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="col-sm-3 control-label" style="padding-left: 0px;">Date Time Format</label>
                                    <div class="col-sm-3">
                                        <select type="text" class="form-control quesiionMandatory-edit" placeholder="Date Time Format" id="date_time_format" name="date_time_format" value="Select Date Time Format" required>
                                        <option value="">Select Date Time Format</option>
                                        <?php
                                       //print_r($selected );die;
                                                
                                        foreach($date_format as $value_cl){
                                            $date_time_format_id = $value_cl['id'];
                                            $date_time_format_name = $value_cl['date_time_format'];
                                            $php_date_time_format_name = $value_cl['php_date_time_format'];
                                            $jquery_date_time_format_name = $value_cl['jquery_date_time_format'];
                                            $pregmatch_date_time_name=$value_cl['pregmatch_date_time'];
                                            ?>
                                        <option <?php echo ($date_time_fomat_selected == $php_date_time_format_name )?"selected='selected'":"" ?> value="<?= $date_time_format_name."@".$php_date_time_format_name."@".$jquery_date_time_format_name."@".$pregmatch_date_time_name;?>"><?=date($php_date_time_format_name);?></option>
                                            <?php
//                                            echo "<pre>";
//                                            print_r($value_cl);
//                                            echo "</pre>";
                                        }
                                        ?>
                                    </select>
                                    </div>
                                </div>
                                
                                 <div class="modal-footer" style="padding-bottom:0px">
                                     <button onclick="//addTrackerDateSetting(<?php echo $tracker_id ?>)" type="submit" class="btn btn-primary">Save</button>
                                    <button onclick="window.location.href='/tracker/settings/<?php echo $tracker_id ?>'"  class="btn btn-primary" type="button">Close</button>
                                </div>
                            </form>
                             
</div>

            </div>
        </div>
    </div>
