<?php
$tracker_details = $trackerRsults['tracker_details'];
$tables = $trackerRsults['tables'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name Tracker Dashboard";
$this->headTitle($title);
?>

<div class="container-liquid">
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <!--                <a class="closethis">Close</a>-->
                <header>
                    <h2 class="heading"><?php echo $this->escapeHtml($title); ?></h2>
                </header>
                <div class="contents boxpadding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'view', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><br/>Home</button>
                                </a>
                            </div>
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'user', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><br/>User</button>
                                </a>
                            </div>
                            <?php
                            foreach ($tables as $key => $value) {
                                $table_name = $value['table_name'];
                                $table_id = $value['table_id'];
                                ?>

                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'table', 'tracker_id' => $tracker_id, 'action_id' => $table_id)) ?>">
                                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br/><?= $table_name; ?></button>
                                    </a>
                                </div>
                                <?
                            }
                            ?>
                            <div class="btn-group" style="float:right" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'newtable', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span><br/>New Table</button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body ">
                            <div  class="clearfix">
                                <div  class="pull-right">
                                    <div class="btn-group" role="group" aria-label="...">
                                        <a href="#" data-toggle="modal" id="audModelAdd" data-target="#addAuditModel">
                                            <button type="button" class="btn btn-default "><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Asign New User</button>
                                        </a>
                                    </div>
                                </div>    
                            </div>    
                            <hr/>
                            <table class="table table-striped">
                                <tr>
                                    <th>Sl No</th>
                                    <th>User Name</th>
                                    <th>Role</th>
                                </tr>
                                <?php
                                $ival = 0;
                                foreach ($users as $user => $values) {
                                    ?>
                                    <tr>
                                        <td><?php $ival++;
                                echo $this->escapeHtml($ival); ?></td>
                                        <td><?php echo $this->escapeHtml($values['u_realname']); ?></td>
                                        <td><?php echo $this->escapeHtml($values['group_name']); ?></td>

                                    </tr>
                                    <?php
                                }
                                ?>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Row End -->
</div>
</div>
<!-- Content Section End -->
</div>
<!-- Right Section End -->
</div>
</div>

<div class="container-liquid">

    <!-- Row End -->
</div>

<div class="modal fade" id="addAuditModel" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog"  style="margin-bottom:0px;" >
        <div class="modal-content" id="modelContentAdd">
            <div class="panel panel-primary" style="margin:0px">
                <div class="panel-heading">Asign user<button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button></div>
                <div style=" padding-left: 10px;">
                    <form data-toggle="validator" id="commentForm" method="get" action="" name="myForm" class="form-horizontal">

                    </form>


                </div>
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function() {
        $("#audModelAdd").click(function() 
        { 
            var html = '';
            html += '<div class="modal-body" id="divBody">'
            html += '<div class="form-group">'
            html += '<label class="col-sm-2 control-label" style="padding-left: 0px;">User</label>'
            html += '<div class="col-sm-8">'
            var tracker_id = '<?= $tracker_id; ?>';
            var data = {
                tracker_id : tracker_id
            }
            var url = "<?php echo $this->url('user', array('action' => 'getusersasign')); ?>";
            $.post(url, data,function(respJson){
                var resp =JSON.parse(respJson);
                var responseCode = resp.responseCode;
                var errMessage = resp.errMessage;
                if(responseCode == 1){
                    $("#status").html('<font color="#088A08">'+errMessage+'</font>');
                }
                else{
                    $("#status").html('<font color="#cc0000">'+errMessage+'</font>');
                }
            });
            
            
            
            html += '<input type="text" class="form-control"  placeholder="User" id="groupName" name="groupName">'
            html += '</div>'
            html += '</div>'
            html += '<div class="modal-footer">'
            html += '<button onclick="addQusetions()" type="button" class="btn btn-primary">Save</button>'
            html += '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>'
            html += '</div>'
            $('#commentForm').html(html);
        });
    });	
</script>