<?php
$tracker_details = $trackerRsults['tracker_details'];
$forms = $trackerRsults['forms'];
//$table_details = $trackerRsults['form_details'];
$form_name = $form_details['form_name'];
$record = $form_details['record_name'];
$tracker_name = $tracker_details['name'];
$title = "$tracker_name Tracker - $form_name";
$this->headTitle($title);


$user_details = $_SESSION['user_details'];
$role_id = $user_details['group_id'];
$tracker_user_groups = @$_SESSION['tracker_user_groups'];
$session_group = @$tracker_user_groups[$tracker_id]['session_group'];
if (! function_exists('array_column')) {
    function array_column(array $input, $columnKey, $indexKey = null) {
        $array = array();
        foreach ($input as $value) {
            if ( ! isset($value[$columnKey])) {
                trigger_error("Key \"$columnKey\" does not exist in array");
                return false;
            }
            if (is_null($indexKey)) {
                $array[] = $value[$columnKey];
            }
            else {
                if ( ! isset($value[$indexKey])) {
                    trigger_error("Key \"$indexKey\" does not exist in array");
                    return false;
                }
                if ( ! is_scalar($value[$indexKey])) {
                    trigger_error("Key \"$indexKey\" does not contain scalar value");
                    return false;
                }
                $array[$value[$indexKey]] = $value[$columnKey];
            }
        }
        return $array;
    }
}
?>

<div class="container-liquid">
    <div class="row">
        <div class="col-xs-12">
            <div class="sec-box">
                <!--                <a class="closethis">Close</a>-->
                <header>
                    <h2 class="heading"><?php echo $this->escapeHtml($title); ?></h2>
                </header>
                <div class="contents boxpadding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="<?php echo $this->url('tracker', array('action' => 'view', 'tracker_id' => $tracker_id)) ?>">
                                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><br/>Home</button>
                                </a>
                            </div>
                            <?
                            if ($role_id == 1 || $session_group == "Administrator") {
                                ?>
                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'settings', 'tracker_id' => $tracker_id)) ?>">
                                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><br/>Settings</button>
                                    </a>
                                </div>
                            <? } ?>
                            <?php
                            foreach ($forms as $key => $value) {
                                $form_name = $value['form_name'];
                                $form_id = $value['form_id'];
                                ?>

                                <div class="btn-group" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'form', 'tracker_id' => $tracker_id, 'action_id' => $form_id)) ?>">
                                        <button type="button" class="btn btn-<?php
                                        if ($action_id == $form_id) {
                                            echo 'info';
                                        } else {
                                            echo 'default';
                                        }
                                        ?>"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><br/><?= $form_name; ?></button>
                                    </a>
                                </div>
                            <?
                            }
                            ?>
                            <?
                            if ($role_id == 1 || $session_group == "Administrator") {
                                ?>
                                <div class="btn-group" style="float:right" role="group" aria-label="...">
                                    <a href="<?php echo $this->url('tracker', array('action' => 'newform', 'tracker_id' => $tracker_id)) ?>">
                                        <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span><br/>New Form</button>
                                    </a>
                                </div>
                            <? } ?>

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div  class="clearfix">
                                <?php $form_name = $form_details['form_name']; ?>
                                <h3><?= "$record - $form_name : #$record_id"; ?></h3>
                                <div  class="pull-right">
                                    <div class="btn-group" role="group" aria-label="...">
                                        <a href="<?php echo $this->url('tracker', array('action' => 'editrecord', 'tracker_id' => $tracker_id, 'action_id' => $action_id, 'subaction_id' => $record_id)) ?>">
                                            <button type="button" class="btn btn-info "><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> Edit <?= $record; ?></button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <hr/>
                            <?php
                            $workflows = $fields_array_val['workflows'];
                            //print_r($workflows);die;
                            $fields = $fields_array_val['fields'];
                            if (array_key_exists(0, $workflows)) {
                                $ival = 0;
                                $id=1;
                                ?>
                                <form id="commentForm" method="post" action="<?php echo $this->url('tracker', array('action' => 'saverecord', 'tracker_id' => $tracker_id, 'action_id' => $action_id)) ?>" name="myForm" class="form-horizontal">
                                    <?
                                    foreach ($workflows as $wfk => $wf_values) {
                                        $workflow_name = $wf_values;
                                        $fields_array = $fields[$workflow_name];
                                      //  print_r($fields_array);
                                      //  die;
                                        $form_records_array = @$form_records['form_data'][0];
                                        $view_self = $fields_array[array_search('User', array_column($fields_array, 'field_type'))]['field_name'];
                                        foreach ($fields_array as $field => $f_values) {
                                            //$f_id = 'f_' . $f_values['field_id'];
                                            $label = $f_values['label'];
                                            $field_name = $f_values['field_name'];
                                            $field_type = $f_values['field_type'];
                                            $options_id = $f_values['code_list_id'];
                                            $record_value = @$form_records_array[$field_name];
                                            $can_view = '';
                                            if ($role_id == 1 || $session_group == "Administrator") {
                                                $can_view = "Yes";
                                            } else if (($workflow_name == $f_values['workflow_name'] && $f_values['can_read'] == "Self") && ($form_records_array[$view_self] == $user_details['u_name'])) {
                                                // echo "here";die;
                                                $can_view = "Yes";
                                            } else {
                                                $can_view = @$f_values['can_read'];
                                            }
                                        }
                                        if ($can_view == 'Yes') {
                                            ?>
                                            <div class="panel panel-default">
                                            <div class="panel-body">
                                                <div id="workflow_div_<?= $id?>">
                                                    <h4><i class="icon-minus" id="icon_data_<?= $id?>"></i><?= " " . $workflow_name; ?></h4>
                                                </div>
                                                <div id="workflow_content_<?= $id?>"  class="box-content">
                                            <!--h4><span class="glyphicon glyphicon-list"
                                                      aria-hidden="true"></span><?= " " . $workflow_name; ?>
                                            </h4-->
                                            <?
                                            foreach ($fields_array as $field => $f_values) {
                                                //$f_id = 'f_' . $f_values['field_id'];
                                                $label = $f_values['label'];
                                                $field_name = $f_values['field_name'];
                                                $field_type = $f_values['field_type'];
                                                $options_id = $f_values['code_list_id'];
                                                $record_value = @$form_records_array[$field_name];
                                                /* $can_view='';
                                                 if ($role_id == 1 || $session_group == "Administrator") {
                                                     $can_view = "Yes";
                                                 } else if (($f_values['can_read'] == "Self") && ($form_records_array[$view_self] == $user_details['u_name'])) {
                                                    // echo "here";die;
                                                     $can_view = "Yes";
                                                 } else {
                                                     $can_view = @$f_values['can_read'];
                                                 }*/
                                                // if ($can_view == 'Yes') {
                                                ?>
                                                <?php if ($field_type == 'Heading') {
                                                ?>
                                            <br>
                                                <div class="col-md-12">
                                                    <h4><?php echo $this->escapeHtml($label); ?></h4>
                                                </div>
                                                <?php
                                                }
                                                else {
                                                    
                                                    if ($field_type == "Formula") {
                                                        $pregmatch_date_time = str_replace("'", "", '/^(\d{4})-(\d{2})-(\d{2}) ([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$/');
                                                        $pregmatch_date = str_replace("'", "", '/^(\d{4})-(\d{2})-(\d{2})$/');
                                                        if (preg_match($pregmatch_date_time, $record_value, $matches)) { 
                                                               // if (checkdate($matches[2], $matches[3], $matches[1])) { 
                                                                        $record_value = date($date_time_formats['php_date_time_format'],strtotime($record_value)); 
                                                              //  } 
                                                        }
                                                        if (preg_match($pregmatch_date, $record_value, $matches)) { 
                                                             //   if (checkdate($matches[2], $matches[3], $matches[1])) { 
                                                                        $record_value = date($date_time_formats['php_date_format'],strtotime($record_value)); 
                                                              //  } 
                                                        }
                                                    }
                                                    if ($field_type == "Formula Date") {
                                                       if($record_value!=''){
                                                                        $record_value = date($date_time_formats['php_date_format'],strtotime($record_value)); 
                                                        }
                                                    }
                                                    if ($field_type == "Date Time") 
                                                        if($record_value!=''){
                                                        $record_value = date($date_time_formats['php_date_time_format'],strtotime($record_value));
                                                        }
                                                    if ($field_type == "Date")
                                                        if($record_value!=''){               
                                                        $record_value = date($date_time_formats['php_date_format'],strtotime($record_value));
                                                        }
                                                    ?>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="col-md-4 control-label"
                                                               style="padding-left: 0px; margin-top:2px"><?php echo $this->escapeHtml($label); ?></label>

                                                               <?php if($field_type == "File" && !empty($record_value) ){
                                                                   $keyname='attachment/attach_'.$tracker_id.'_'.$action_id.'/'.$record_value;
                                                                   $filename=$record_value;
                                                                   ?>
                                                                   <div class="col-md-8">
                                                                        <a href="<?php echo $this->url('aws', array('action' => 'downloadFilesFromAws', 'keyname'=>base64_encode($keyname),'filename'=>base64_encode($filename))) ?>" download="<?=$record_value; ?>" ><span class="link" style="color: #0000aa;">Download supporting file</span></a>
                                                                </div>
                                                            <?php 
                                                            } else {?>
                                                                
                                                            <div class="col-md-8">
                                                                <?= $record_value; ?>
                                                            </div>
                                                            <?
                                                            if ($field_type == "Check Box") {
                                                                if (strlen(@$record_value) > 0) {
                                                                    ?>
                                                                    <div>
                                                                        <label>Comment : </label>
                                                                        <?= @$form_records_array["comment_checkbox_$field_name"] ?>
                                                                    </div>
                                                                <?
                                                                }
                                                            }
                                                            }
                                                        ?>
                                                    </div>
                                                </div>
                                            <?php
                                            }
                                        }
                                        ?>
                                                    </div>
                                        </div>
                                        </div>
                                    <?php
                                    }
                                        $id++;
                                    }

                                    ?>
                                    <span id="status"></span>
                                </form>
                            <?php
                            } else {
                                echo "Fields not exist.";
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Row End -->
</div>
</div>
<!-- Content Section End -->
</div>
<!-- Right Section End -->
</div>
</div>
<div class="container-liquid">

    <!-- Row End -->
</div>


<script>
    $(document).ready(function() {

        $('.control-label').css('margin-top','10px');
        $('.col-md-6').css('margin-top','10px');
        $('.col-md-4').css('margin-top','10px');
        $('.col-md-8').css('margin-top','10px');
    });

    $('[id^="workflow_div_"]').click(function () {
        var id=this.id;
        var splite=id.split('_');
        var last_id=splite[2];
        if ($('#workflow_content_'+last_id).is(":hidden")) {
            $('#workflow_content_'+last_id).slideDown('slow');
            $('#icon_data_'+last_id).removeClass('icon-plus').addClass('icon-minus');
        } else {
            $('#workflow_content_'+last_id).slideUp('slow');
            $('#icon_data_'+last_id).removeClass('icon-minus').addClass('icon-plus');
        }
    });

</script>
