<?php
$title = "Report Filter";
$this->headTitle($title);
$reportName = "";
foreach($reportDetails as $report) {
    $reportName = $report['report_name'];
}
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
        <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Reports</span></li>
        <li class="active"><span>Filters for <?=$reportName;?></span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header"><b>Filters for <?=$reportName;?></b></div>
            <form id="filterForm" method="post" action="" name="filterForm" class="form-horizontal">
            <div class="card-body"> 
                <?php if (!empty($reportDetails)) { foreach ($reportDetails as $report) { if ($report['report_filters'] != '') {$filters = json_decode($report['report_filters']); //echo "<pre>"; print_r($filters); die;?>
                    <?php if ($filters != '') { foreach ($filters as $filter) { ?>
                        <?php 
                        switch ($filter->type) {
                            case 'monthrange':
                            ?>
                            <div class="form-group row">
                                <label class="col-sm-5 col-form-label"><?=$filter->label;?>
                                    <?php if ($filter->required == 'true') { ?>
                                    <span class="error ml-1">*</span>
                                    <?php } ?>
                                </label>
                                <div class="col-sm-6">
                                    <input autocomplete='off' readonly="true" type='text' typeOffield="monthrange" class='monthrange form-control' label="<?=$filter->label;?>" id='<?=$filter->field;?>' name='<?=$filter->field;?>'<?=($filter->required == 'true')? "mandatory='1'":"mandatory='0'";?> />
                                    <div class="error" id="<?=$filter->field;?>_error"></div>
                                </div>
                            </div>
                            <?php
                                break;
                            case 'date':
                                ?>
                                <div class="form-group row">
                                    <label class="col-sm-5 col-form-label"><?=$filter->label?>
                                        <?php if ($filter->required == 'true') { ?>
                                        <span class="error ml-1">*</span>
                                        <?php } ?>
                                    </label>
                                    <div class="col-sm-6">
                                        <input autocomplete='off' readonly="true" type='text' typeOffield="date" class='daterange form-control' label="<?=$filter->label;?>" id='<?=$filter->field;?>' name='<?=$filter->field;?>' <?=($filter->required == 'true')? "mandatory='1'":"mandatory='0'";?> <?php if (isset($filter->format)) {?>date-format="<?=addslashes($filter->format);?>" <?php } ?>/>
                                        <div class="error" id="<?=$filter->field;?>_error"></div>
                                    </div>
                                </div>
                            <?php
                                break;
                            case 'text':
                                ?>
                                <div class="form-group row">
                                    <label class="col-sm-5 col-form-label"><?=$filter->label?>
                                        <?php if ($filter->required == 'true') { ?>
                                        <span class="error ml-1">*</span>
                                        <?php } ?>
                                    </label>
                                    <div class="col-sm-6">
                                        <input autocomplete='off' type='text' typeOffield="text" class='form-control' label="<?=$filter->label;?>" id='<?=$filter->field;?>' name='<?=$filter->field;?>' <?=($filter->required == 'true')? "mandatory='1'":"mandatory='0'";?>/>
                                        <div class="error" id="<?=$filter->field;?>_error"></div>
                                    </div>
                                </div>
                            <?php
                                break;
                            case 'select':    
                            ?>
                                <div class="form-group row">
                                    <label class="col-sm-5 col-form-label"><?=$filter->label?>
                                        <?php if ($filter->required == 'true') { ?>
                                        <span class="error ml-1">*</span>
                                        <?php } ?>
                                    </label>
                                    <div class="col-sm-6">
                                        <select class='selectpicker form-control' multiple typeOffield="select" data-live-search="true" data-actions-box="true" title="Select <?=$filter->label;?>" data-container="body" id='<?=$filter->field;?>' label="<?=$filter->label;?>" name='<?=$filter->field;?>' <?=($filter->required == 'true')? "mandatory='1'":"mandatory='0'";?>/>
                                            <?php if (isset($filter->options)) { 
                                                        foreach ($filter->options as $key=>$value) { ?>
                                                        <option value="<?=$key;?>"><?=$value;?></option>
                                            <?php }} else if (isset($filter->codelist_id)) { $app = $this->AppHelper(array("codelist_id" =>intval($filter->codelist_id))); 
                                                        if (isset($app[4])) { foreach ($app[4] as $key=>$value) { ?>
                                                        <option value="<?=$value['value'];?>"><?=$value['label'];?></option>
                                            <?php }}} else if (isset($filter->data)) { $app = $this->AppHelper(array("dataQuery" =>$filter->data));
                                                        if (isset($app[5])) { foreach ($app[5] as $key=>$value) { ?>
                                                        <option value="<?=$value['value'];?>"><?=$value['value'];?></option>
                                            <?php }}} ?>
                                        </select>
                                        <div class="error" id="<?=$filter->field;?>_error"></div>
                                    </div>
                                </div>
                            <?php
                                break;
                            case 'checkbox':    
                            ?>
                                <div class="form-group row">
                                    <label class="col-sm-5 col-form-label"><?=$filter->label?>
                                        <?php if ($filter->required == 'true') { ?>
                                        <span class="error ml-1">*</span>
                                        <?php } ?>
                                    </label>
                                    <div class="col-sm-6">
                                        <select class='selectpicker form-control' multiple typeOffield="checkbox" data-live-search="true" data-actions-box="true" title="Select <?=$filter->label;?>" data-container="body" id='<?=$filter->field;?>' label="<?=$filter->label;?>" name='<?=$filter->field;?>' <?=($filter->required == 'true')? "mandatory='1'":"mandatory='0'";?>/>
                                            <?php if (isset($filter->options)) { 
                                                        foreach ($filter->options as $key=>$value) { ?>
                                                        <option value="<?=$key;?>"><?=$value;?></option>
                                            <?php }} else if (isset($filter->codelist_id)) { $app = $this->AppHelper(array("codelist_id" =>intval($filter->codelist_id))); 
                                                        if (isset($app[4])) { foreach ($app[4] as $key=>$value) { ?>
                                                        <option value="<?=$value['value'];?>"><?=$value['label'];?></option>
                                            <?php }}} else if (isset($filter->data)) { $app = $this->AppHelper(array("dataQuery" =>$filter->data));
                                                        if (isset($app[5])) { foreach ($app[5] as $key=>$value) { ?>
                                                        <option value="<?=$value['value'];?>"><?=$value['label'];?></option>
                                            <?php }}} ?>
                                        </select>
                                        <div class="error" id="<?=$filter->field;?>_error"></div>
                                    </div>
                                </div>
                            <?php
                                break;
                        }?>
                    <?php } ?>

                   <?php }?>
                <?php }}}?>
                
            </div>
            <div class="card-footer">
                <div class="form-group row">
                    <div class="offset-sm-5">
                        <button type="submit" class="btn btn-primary ml-3">Generate Report</button>
                        <button type="button" class="btn btn-default" onclick="window.location.href='/dashboard/<?php echo $trackerId;?>/<?php echo $formId;?>'">Cancel</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<script> 
    var trackerId="<?php echo $trackerId;?>";
    var formId="<?php echo $formId;?>";
    var reportId="<?php echo $reportId;?>";
</script>
<?php
    $this->inlineScript()
            ->appendFile($this->basePath() . '/assets/jquery.redirect.js', 'text/javascript')
            ->appendFile($this->basePath() . '/js/module/common/report/filter.js', 'text/javascript');