<?php
$title = "Report";
$this->headTitle($title); 
$reportName = "";
foreach($reportDetails as $report) {
    $reportName = $report['report_name'];
}
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
        <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Reports</span></li>
        <li class="active"><a href="/report/filter/<?=$trackerId;?>/<?=$formId;?>/<?=$reportId;?>"><span>Filters for <?=$reportName;?></span></a></li>
        <?php if ($reportName != '') {?>
        <li class="active"><span><?=$reportName;?></span></li>
        <?php } ?>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card card-default mb-2">
            <div class="card-header">
                <div class="row mb-3"><?php echo $reportName; if (strlen($headBreadcrumb) > 4) { echo " for ".substr($headBreadcrumb, 4);}?></div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-0">Page Size:</div>
                    <div class="ml-2" style="width:80px!important;">
                        <select onchange="onPageSizeChanged()" id="page-size" class="form-control">
                            <option value="5" selected>5</option>
                            <option value="10">10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                            <option value="500">500</option>
                            <option value="1000">1000</option>
                        </select>
                    </div>
                    <div class="col-sm-2 ml-auto mb-2">
                        <div class="btn-toolbar">
                            <div class="btn-group toolbar-icons ml-auto" role="group">
                              <div class="btn-group" role="group">
                                  <button type="button" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="lnr icon-arrow-down-square"></i>
                                  </button>
                                  <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a class="dropdown-item" onclick="downloadCSV();">Export to CSV</a></li>
                                    <li><a class="dropdown-item" onclick="downloadEXCEL();">Export to Excel</a></li>
                                  </ul>
                              </div>
                              <!--<button type="button" class="btn btn-icon" id="dt_reload" onclick="refresh();"><i class="lnr icon-refresh"></i></button>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div id="myGrid" class="ag-theme-material"></div>
            </div>
        </div>
    </div>
</div>
<script> 
    var trackerId="<?php echo $trackerId;?>";
    var formId="<?php echo $formId;?>";
    var reportId="<?php echo $reportId;?>";
    var condition = "<?php echo $condition;?>";
    var headBreadcrumb = "<?php echo $headBreadcrumb;?>"
</script>
<form action="" id="downloadReport" method="POST">
    <input type="hidden" name="condition" value="<?=$condition;?>" />
    <input type="hidden" name="headBreadcrumb" value="<?=$headBreadcrumb;?>" />
    
</form>

 <?php 
    $this->inlineScript()
            ->appendFile($this->basePath() . '/js/module/report/report.js', 'text/javascript');