<?php
$trackerDetails = $trackerResults['tracker_details'];
$forms = $trackerResults['forms'];
$trackerName = $trackerDetails['name'];
$title = "$trackerName - User";
$this->headTitle($title);
echo $this->formElement($form->get('t_hidden'));
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Settings</span></li>
        <li><span>Tracker Settings</span></li>
        <li><span><a href="/user/user_management/<?php echo $trackerId;?>">User Management</a></span></li>
        <li class="active"><span>Add User</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6>Add User</h6>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label class="col-sm-4"></label>
                    <div id="userErrorMessages" class="error col-sm-6"></div>
                </div>
                <form id="userAddForm" method="post" name="myForm">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">User Name<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" <?php if ($userId > 0) { echo 'readonly'; ?> value="<?php echo $result[0]['u_name'] ?>" <?php } ?> placeholder="Username" id="u_name" name="u_name" required>
                            <div class="error" id="forUserId"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">User Email<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" value="" placeholder="User Email" id="email" name="email" required>
                            <div class="error" id="forEmail"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Role Name<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                            <select class="selectpicker form-control" multiple data-live-search="true" data-actions-box="true" id="role_id" name="role_id" title="Select role" data-container="body" required>
                                <?php
                                $selected = '';
                                foreach ($groups as $opt => $opt_values) {
                                    $group_id = $opt_values['rid'];
                                    foreach ($result as $res) {
                                        if ($userId > 0 && $group_id == $res['rid']) {
                                            $selected = 'selected';
                                            break;
                                        } else {
                                            $selected = '';
                                        }
                                    }
                                    $group_name = $opt_values['role_name'];
                                    ?>
                                    <option <?php echo $selected ?> value="<?php echo $this->escapeHtml($group_id); ?>"><?php echo $this->escapeHtml($group_name); ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <div class="error" id="forRoleId"></div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                        <div class="col-sm-6">
                           <textarea id="reason" class="form-control" placeholder="Reason for change" name="addcomment"></textarea>
                           <div id="forReason" class="error"></div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group row">
                            <?php if ($userId == 0) { ?>
                            <div class="offset-sm-4">
                                <button id ="savebtn" type="button" class="btn btn-primary ml-2" onclick="addNewUser(<?php echo $userId ?>)">Save</button>
                                <button onclick="window.location.href='/user/user_management/<?php echo $trackerId ?>'" type="button" class="btn btn-default">Cancel</button>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script> 
    var trackerName='<?php echo $trackerName ?>';
    var userId='<?php echo $userId ?>';
</script>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/module/common/user/addUser.js', 'text/javascript');