<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();
$userContainer = $session->getSession('user');
$forms = isset($trackerResults['forms'])?$trackerResults['forms']:array();
$trackerDetails = isset($trackerResults['tracker_details'])?$trackerResults['tracker_details']:array();
$trackerName = isset($trackerDetails['name'])?$trackerDetails['name']."":"";
$title = "$trackerName Users";
$this->headTitle($title);
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><span>Settings</span></li>
        <li><span>Tracker Settings</span></li>
        <li class="active"><span>User Management</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6 class="col-md-6 float-left">List of Users</h6>
                <span class="col-md-6">
                   <button type="button" class="btn btn-primary float-right" onclick="window.location.href='/user/add/<?php echo $trackerId ?>'">Add New User</button>
                </span>
            </div>
            <div class="card-body">
                <?php
                $flashMessage = $this->flashMessenger()->getMessages();
                if (count($flashMessage) && isset($flashMessage[0]['success'])) {
                    echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                }
                ?>
                <div class="table-responsive">
                    <table id="list_of_users" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>User Name</th>
                                <th>User Email</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody id="clientbody">
                            <?php foreach ($user as $users => $values) { ?>
                                <tr>
                                    <td>
                                        <button type="button" onclick="window.location.href='/user/view/<?php echo $trackerId ?>/<?php echo $values['u_id'] ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-eye" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" onclick="window.location.href='/user/edit/<?php echo $trackerId ?>/<?php echo $values['u_id'] ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-pencil" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" data-toggle="modal"  <?php if ($values['u_id'] != $userContainer->u_id) { ?> data-target="#deleteUser_<?php echo $values['u_id']; ?>" <?php } else { ?> data-target="#self_delete" <?php } ?> class="btn btn-default" aria-label="Left Align" onclick="reloadPopUp('<?php echo $values['u_id']; ?>')">
                                            <span class="lnr icon-trash2" aria-hidden="true"></span>
                                        </button>
                                        <?php if ($values['u_id'] != $userContainer->u_id) { ?>
                                        <!-- Modal -->
                                        <div class="modal fade" id="deleteUser_<?php echo $values['u_id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteUserModal" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="form-group row">
                                                            <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                                                            <div class="col-sm-7">
                                                                <textarea id="reason_<?php echo $values['u_id']; ?>" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>   
                                                                <span id="forReason_<?php echo $values['u_id']; ?>" class="error"></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button id="reasonfordelete" onclick="deleteUserAction('<?php echo $values['u_id']; ?>', '<?php echo $trackerId; ?>', '<?php echo $values['u_name']; ?>')" type="button" class="btn btn-primary">Delete</button>
                                                        <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <?php } ?>
                                    </td>
                                    <td><?php echo $this->escapeHtml($values['u_name']); ?></td>
                                    <td><?php echo $this->escapeHtml($values['email']); ?></td>
                                    <td><?php echo $this->escapeHtml($values['status']); ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="self_delete" tabindex="-1" role="dialog" aria-labelledby="deleteSelfUserModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Warning!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    System will not allow you to delete your own account. Please contact your administrator.
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<?php 
    $this->inlineScript()->appendFile($this->basePath() . '/js/module/common/user/listUser.js', 'text/javascript');
