<?php 
use Session\Container\SessionContainer;
$session = new SessionContainer();
$userSession = $session->getSession('user');
$configSession = $session->getSession('config');
if(isset($_SESSION['timestamp']) && (time() - $_SESSION['timestamp'] > $configSession->time_out_limit)) { //subtract new timestamp from the old one 
    $auditLog = new \Common\Audit\Model\Audit; //new \Application\Controller\IndexController;
    $userDetails = $userSession->user_details;
    $session->clearSession('user');
    $auditLog->saveToLog(0, isset($userDetails['email'])?$userDetails['email']:'', 'logout', '','','time out logout','logout success',0);
    unset($_SESSION['timestamp']);
    $url = $configSession->end_session_endpoint;
    header("Location: ".$url); //redirect to logout url
    exit;
}
echo $this->doctype();
$var = $this->layout()->getVariables();
$app = $this->AppHelper($var);
$appName = isset($app[8]['nameOfTrace'])?$app[8]['nameOfTrace']:"Trace";
?>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type: text/html; charset=utf-8" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
	<?php echo $this->headTitle('' . $this->translate($appName))->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/assets/bootstrap-select-1.13.2/dist/css/bootstrap-select.min.css')
                ->appendStylesheet($this->basePath() . '/assets/DataTables-1.10.18/datatables.min.css')
                ->appendStylesheet($this->basePath() . '/assets/daterangepicker/css/daterangepicker.css')
                ->appendStylesheet($this->basePath() . '/assets/ag-grid/dist/styles/ag-grid.css')
                ->appendStylesheet($this->basePath() . '/assets/ag-grid/dist/styles/ag-theme-material.css')
                ->appendStylesheet($this->basePath() . '/assets/custom/css/style.css')
                ->appendStylesheet($this->basePath() . '/assets/custom/css/widget.css')
                ->appendStylesheet($this->basePath() . '/assets/summernote/summernote-bs4.css')
                ->appendStylesheet($this->basePath() . '/assets/custom/css/loader.css')
                ->appendStylesheet($this->basePath() . '/assets/multiselect/css/jquery.multiselect.css')
                ->appendStylesheet($this->basePath() . '/assets/multiselect/css/select2.min.css');
	?>
	<!-- Scripts -->
	<?php echo 
            $this->headScript()
            ->appendFile($this->basePath() . '/assets/jQuery-3.3.1/jquery-3.3.1.min.js', 'text/javascript')
            ->appendFile($this->basePath() . '/assets/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
            ->appendFile($this->basePath() . '/assets/cookie.min.js', 'text/javascript')
            //->appendFile($this->basePath() . '/assets/selectize/js/selectize.min.js', 'text/javascript')    
            ->appendFile($this->basePath() . '/assets/globalErrorMessages.js', 'text/javascript')
            ->appendFile($this->basePath() . '/assets/ag-grid/dist/ag-grid-community.min.js', 'text/javascript');
            
	?>
</head>
<body>
<?php if (isset($userSession->u_id)) { ?>
    <?php echo $this->partial('navbar');?>   
    <div id="wrapper-profile">
        <?php echo $this->partial('sidebar');?> 
        <div class="page-wrapper pb-0">
            <div class="page-content mb-3">
<?php } ?>
                
<?php if (!$this->layout()->isHavingPermission) { ?> 
<style>
img {
    height: auto;
    max-width: 100%;
    vertical-align: middle;
    border: 0;
}
</style>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li class="active"><span>Access Denied</span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body"> 
        <div class="row">
            <div class="widget box">
                <div class="widget-content align-center">
                    <div class="alert alert-warning">
                        <h1></h1>
                        <div class="banner">
                            <img src="/assets/403_Error.png" alt="Access Denied">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>        
<?php } else { echo $this->content; } ?>
                
<?php if (isset($userSession->u_id)) { ?>
            </div>
        <?php include_once "footer.phtml"; ?> 
        </div>
    </div>     
<?php } ?>
<?php
echo $this->inlineScript()
    ->prependFile($this->basePath() . '/assets/moment/momentjs-business.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/bootstrap-select-1.13.2/dist/js/bootstrap-select.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/bootstrap-4.2.1/dist/js/bootstrap.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/jquery-validation/dist/jquery.validate.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/daterangepicker/js/daterangepicker.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/DataTables-1.10.18/datatables.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/DataTables-1.10.18/js/jquery.dataTables.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/moment/moment.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/jQuery-3.3.1/jquery.app.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/jQuery-3.3.1/jquery.nicescroll-3.7.6.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/popper/popper.min.js', 'text/javascript')
    ->appendFile($this->basePath() . '/assets/multiselect/js/jquery.multiselect.min.js', 'text/javascript')
    ->appendFile($this->basePath() . '/assets/multiselect/js/select2.min.js', 'text/javascript');
?>
<script>
$('.dropdown-menu a.dropdown-toggle').on('click', function(e) {
  if (!$(this).next().hasClass('show')) {
    $(this).parents('.dropdown-menu').first().find('.show').removeClass("show");
  }
  var $subMenu = $(this).next(".dropdown-menu");
  $subMenu.toggleClass('show');


  $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function(e) {
    $('.dropdown-submenu .show').removeClass("show");
  });

  return false;
});
$(document).ready(function () {

    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
    });

});
function changeSessionRole(tracker_id, group_id, group_name){
        $('#loading').show();
        var data = {
                tracker_id : tracker_id,
                group_id : group_id,
                group_name : group_name,
        };
        var url = "/tracker/change_role";
        $.post(url, data,function(respJson){
            if (respJson == 'success') {
                location.reload();
                return false;
            }
            $('#loading').hide();
        });
}
$(document).ready(function() {
    $('#clientdata').dataTable( {
            "bDestroy": true,
            "bScrollInfinite": true,
            "bScrollCollapse": true,
            "paging":         true,
            "aLengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]]
    });
});
</script>

</body>
</html>
