<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();

$configContainer = $session->getSession('config');
$allowedFileSize=$configContainer->config['importFileSize'];
$title = "Signal Calendar";
$this->headTitle($title);
$workflowLink = json_encode($showWorkflowLink);
?>
<div class="card">
    <div class="card-body">
        <?php
        $flashMessage = $this->flashMessenger()->getMessages();
        if (count($flashMessage) && isset($flashMessage[0]['success'])) {
            echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
        }
        ?>        
        <p class="alert-warning" id="alert"></p>
        <div class="error" id="errorcsv"></div>
        <div class="card">
            <div class="card-header">Import Signal Calendar File</div>
            <div id="part1">
            <form method='post' action='' enctype="multipart/form-data">
                <div class="modal-body">
                      <div class="input-group">
                        <div class="custom-file">
                          <input type="file" class="custom-file-input form-control" id="importCsvFile" aria-describedby="addon-wrapping" name="importCsvFile" accept=".csv,.xls,.xlsx">
                          <label class="custom-file-label" for="importCsvFile">Choose file</label>
                        </div>
                      </div>
                  <div class="error" id="ImportCsvFileMsg">
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" id="btnsigcalImport">Import</button>
                </div>
            </form>
            </div>
            </div>
    </div>

            
<div class="pagebar container-fluid col-md-12"> 
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li><a href="/dashboard/<?=$trackerId;?>/<?=$formId;?>"><span>Dashboard</span><?php if ($label != '') { ?></a><?php } ?></li>
        <?php if ($label != '') { ?>
            <li class="active"><span><?php echo 'Signal Calendar' ?></span></li>
        <?php } ?>
    </ol>
</div>
<div class="card">
<div class="card-header" >Signal Calendar File List</div>
    <div class="card-body">
        
    <!--<div id='alert_deleteRecord' ></div>-->
        <div class="card card-default mb-2">
            <div class="card-body">
                <div class="row">
                    <div class="div-lable">
                        <label style="margin-top: 0.5%;">Show:</label>
                        <div class="showlabel" style="display: inline-block;">
                            <select onchange="onPageSizeChanged()" id="page-size" class="form-control">
                                <option value="5" selected>5</option>
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                                <option value="500">500</option>
                                <option value="1000">1000</option>
                            </select>
                        </div>
                        <label style="margin-top: 0.5%;">&nbsp;Entries:</label>
                    </div>
                    <div class="ml-auto float-right" style="margin-bottom: 10px; margin-right: 10px;">
                </div>
            </div>
            <div id="myGrid" class="ag-theme-material w-100 "></div>
        </div>
    </div>
    </div>
</div>
<div class="modal fade" id="deleteRecordModel" tabindex="-1" role="dialog" aria-labelledby="deleteRecord" aria-hidden="true"> 
    <div class="modal-dialog modal-dialog-centered" role="document"> 
        <div class="modal-content"> 
            <div class="modal-header"> 
                <h5 class="modal-title" id="exampleModalLongTitle">Restore Confirmation</h5> 
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"> 
                    <span aria-hidden="true">&times;</span> 
                </button> 
            </div> 
            <div class="modal-body"> 
                <input type="hidden" id="href" name="href" value=""/>
                <div class="form-group row"> 
                    <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label> 
                    <div class="col-sm-7"> 
                        <textarea id="reason" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>    
                        <span id="forReason" class="error"></span> 
                    </div> 
                </div> 
            </div> 
            <div class="modal-footer"> 
                <button id="reasonfordelete" type="button" class="btn btn-primary">Restore</button> 
                <button class="btn btn-default" type="button" data-dismiss="modal">Close</button> 
            </div> 
        </div> 
    </div>  
</div>
<script> 
    var trackerId="<?php echo $trackerId;?>";
    var formId="<?php echo $formId;?>";
    var type="<?php echo $type;?>";
    var filter="<?php echo $filter;?>"; 
    var canDelete = "<?php echo $canDelete;?>";
    var canEdit = "<?php echo $canEdit;?>";
    var canRead = "<?php echo $canRead;?>";
    var workflowLink = '<?php echo $workflowLink;?>';
    var dashboardId = '<?php echo $dashboardId;?>';
    var asId = '<?php echo $asId;?>';
    
    $(function(){
        setTimeout(function(){
            $("#fashMessage").fadeTo(500, 0).slideUp(500, function () {
            });
        }, 5000);
    });
</script>
 <?php 
    $this->inlineScript()->appendFile($this->basePath() . '/js/module/sigtrace/signalcalendar/list.js', 'text/javascript');
