<?php
$title = "Dashboard";
$this->headTitle($title);
?>
<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
        <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
        <li class="active"><span><?=$title;?></span></li>
    </ol>
</div>
<div class="card" id="reports">
    <div class="card-body">
        <div class="row">
            <?php if (!empty($filters)) { ?>
            <div class="col-sm-2 ml-auto">
                <select v-model="filter" class="form-control" v-on:change="{{ loadData }}">
                    <?php foreach ($filters as $filter) {?>
                    <option value="<?=$filter['filter_name'];?>"><?=$filter['filter_label'];?></option>
                    <?php } ?>
                </select>
            </div>
            <?php } ?>
        </div>
        <div class="card container-fluid mt-2">
            <div class="card-body">
                <div v-if="loading" class="loading">
                    <img src="/assets/dashboard_spinner.gif" width="15%" class="mx-auto d-block" alt="loading..." />
                </div>
                <div v-if="!loading" class="none" id="body-data">
                    <div class="card-columns">
                        <div v-if="data.length > 0" class="card btn-primary" v-for="rep in data" v-bind:repType="rep.type" @click="showLists('<?=$trackerId;?>','<?=$formId;?>', rep.type)" > 
                            <div class="card-body">
                                <h6 class="text-white">{{ rep.name }} <span class="float-right">{{ rep.count }}</span></h6>
                            </div>
                        </div>
                        <div v-if="data.length <= 0">Dashboard data is not available.</div>
                    </div>
                    <div v-if="footerReports.length > 0">
                        <ul class="list-unstyled">
                            <hr/>
                            <li v-for="rep in footerReports"><span>{{ rep.name }} - {{ rep.count }}</span></li>
                        </ul>
                    </div>
                </div>   
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var trackerId = '<?=$trackerId;?>';
    var formId = '<?=$formId;?>';
</script>
<?php
$this->inlineScript()
        ->appendFile($this->basePath() . '/assets/Vue/vue.min.js')
        ->appendFile($this->basePath() . '/assets/Vue/vue-resource.min.js')
        ->appendFile($this->basePath() . '/js/module/dashboard/app.js');
