<?php
$title = 'Customer';
$this->headTitle($title);
?>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
      <li class="active"><span><?php echo $this->escapeHtml($title); ?></span></li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="card">
            <div  class="card-header">
                <h6 class="col-md-6 float-left">List of Customers</h6>
                <span class="col-md-6">
                   <button type="button" class="btn btn-primary float-right" onclick="window.location.href='/customer/add'">Add New Customer</button>
                </span>
            </div>
            <div class="card-body">
                <?php
                $flashMessage = $this->flashMessenger()->getMessages();
                if (count($flashMessage)) {
                    if (isset($flashMessage[0]['success'])) {
                        echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-success" id="fashMessage">'.$flashMessage[0]['success'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                    } else if (isset($flashMessage[0]['error'])) {
                        echo '<div class="contents boxpadding"><div class="alert alert-dismissable alert-danger" id="fashMessage">'.$flashMessage[0]['error'].'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button></div></div>';
                    }
                }
                ?>
                <?php
                if (array_key_exists(0, $customers)) {
                ?>
                <div class="table-responsive">
                    <table id="customerData" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>Customer Name</th>
                                <th>Email ID</th>
                            </tr>
                        </thead>
                        <tbody id="clientbody">
                            <?php
                            $ival = 0;
                            foreach ($customers as $customer) {
                                $val = 1;
                                ?>
                                <tr>
                                    <td>
                                        <button type="button" onclick="window.location.href='/customer/edit/<?php echo $customer['client_id'] ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-pencil" aria-hidden="true"></span>
                                        </button>
                                        <button type="button" onclick="window.location.href='/customer/view/<?php echo $customer['client_id'] ?>'" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-eye" aria-hidden="true"></span>
                                        </button>
                                         <button type="button" onclick="deleteClient('<?php echo $customer['client_id'] ?>')" class="btn btn-default" aria-label="Left Align">
                                            <span class="lnr icon-trash2" aria-hidden="true"></span>
                                        </button>
                                    </td>
                                    <td><?php echo stripslashes($customer['client_name']); ?></td>
                                    <td><?php echo stripslashes($customer['client_email']); ?></td>
                                </tr>
                                <?php
                            }
                            ?>
                        </tbody>
                    </table>
                </div>
                <?php
                } else {
                    echo "No records found.";
                }
                ?>
            </div>
        </div>
    </div>
</div>
<!-- Delete Customer Popup -->
<div class="modal fade" id="deletecommentasreason" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" id="modelContentdelete"> 
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div> 
            <div class="modal-body">
                <input type="hidden" id="customerIdTodelete" value=""/>
                <div class="form-group row">
                    <label class="col-sm-4"></label>
                    <div id="customerDeleteErrorMessages" class="error col-sm-6"></div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Reason for change<span class="error ml-1">*</span></label>
                    <div class="col-sm-7">
                        <textarea id="addcommentfordelete" class="form-control" placeholder="Reason for change." name="addcomment"></textarea>   
                        <span id="commenterrorfordelete" class="error"></span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="reasonfordelete"  type="button" class="btn btn-primary">Delete</button>
                <button class="btn btn-default" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/module/common/customer/customer.js');