<?php
use Session\Container\SessionContainer;
$session = new SessionContainer();
$configContainer = $session->getSession('config');
$allowedFileSize=$configContainer->config['uploadFileSize'];
$userSession = $session->getSession("user");
$user_details = $userSession->user_details['u_name'];
?>
<input type="hidden" id="trackerId" value="<?=$tracker_id?>"/>
<input type="hidden" id="formId" value="<?=$action_id?>"/>
<input type="hidden" id="recordId" value="<?=$record_id?>"/>
<input type="hidden" id="workflowId" value="0"/>
<input type="hidden" id="currentUser" value="<?=$user_details?>"/>

<div class="pagebar container-fluid col-md-12">
    <!-- Sidebar Toggle -->
    <button type="button" class="pagebar-toggle navbar-toggle pull-left">
      <span class="pagebar-arrow"></span>
    </button>
    <ol class="breadcrumb">
    <li><?php if ($label != '') { ?><a href="/dashboard/<?=$tracker_id;?>/<?=$action_id;?>"><?php } ?><span>Dashboard</span><?php if ($label != '') { ?></a><?php } ?></li>
        <?php if ($label != '') { ?>
            <li><a href="/dashboard/list/<?=$tracker_id;?>/<?=$action_id;?>/<?=$type?>/<?=$filter?>"><?php echo $this->escapeHtml(strtoupper($label)); ?></a></li>
        <?php } ?>
        <li class="active"><span>Edit Record #<?php echo $record_id;?></span></li>
    </ol>
</div>

<div class="card">
  <div class="card-body">
    <div class="card card-default mb-2">
        <div class="card-body">
        <div id="accessHeader"></div>
        <form id ="workflowForm" enctype='multipart/form-data' class='workflowFormClass'>
            <div class="row">
            
              <ul class="nav nav-tabs" id="myTab" role="tablist">
              <?php foreach($workflow as $key => $value) { 
                $input = (preg_replace("/[^a-zA-Z]+/", "", $value['workflow_name']));
                if ($value['can_update']=='Yes'|| $value['can_read']=='Yes') { ?>
                
                <li class="nav-item">
                  <a class="nav-link" id="<?=$input;?>-tab" data-toggle="tab" href="#workflow<?=$value['workflow_id'];?>" role="tab" wid="<?=$value['workflow_id'];?>" aria-controls="<?=$input;?>"><b><?=$value['workflow_name'];?></b></a>
                </li>
                <?php $canUpdate=isset($value['can_update'])? $value['can_update']:"No";?>
                <input type="hidden" id="canUpdate" value="<?php echo $canUpdate?>"/>
              <?php }} ?>
                              
              </ul>
            </div>
            <div class="tab-content" id="myTabContent">
            
            <div id="alertWorkflow"></div>
            
            
            <?php foreach($workflow as $key => $value) { 
            $input = strtolower(preg_replace("/[^a-zA-Z]+/", "", $value['workflow_name']));
             if ($value['can_update']=='Yes' || $value['can_read']=='Yes') { ?>
              <div class="tab-pane fade" id="workflow<?=$value['workflow_id'];?>" role="tabpanel" aria-labelledby="<?=$input;?>-tab">
                
                    <div class="form-group row" id="fieldsDiv<?=$value['workflow_id'];?>">
                    </div>

                    <div class="form-group" id="buttonDiv<?=$value['workflow_id'];?>">
                        <div class="row float-right" id="submitResetCancelButton">
                          <div class="mx-auto" style="width: 80px;">
                            <button type="submit" class="btn btn-primary" id="submitButton<?=$value['workflow_id'];?>">Save</button>
                          </div>
                          <div class="mx-auto" style="width: 80px;">
                            <button type="reset" class="btn btn-danger" >Reset</button>
                          </div>
                          <div class="mx-auto" style="width: 80px;">
                            <a href="<?php echo $this->url('dashboard', array('action' => 'list', 'tracker_id' => $tracker_id,'form_id' => $action_id, 'type' => $type, 'filter' => $filter)) ?>" id="cancel" name="cancel" class="btn btn-default">Cancel</a>
                          </div>
                        </div>
                    </div>
                    
              </div>
              <?php }}?>
            </div>
            </form>
          </div>
    </div>
  </div>
</div>

<div class="modal fade" id="tabConfirmation" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirm</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure want to leave this page? You have changes that have not been saved.</p>
        </div>
        <div class="modal-footer">
          <button type="button" id="stayOnPage" class="btn btn-primary" data-dismiss="modal">Stay on Page</button>
          <button type="button" id="leavePage" class="btn btn-default" data-dismiss="modal">Leave Page</button>
        </div>
      </div>
    </div>
</div>

<script>
  var tracker_id="<?php echo $tracker_id;?>";
  var form_id="<?php echo $action_id;?>";
  var record_id="<?php echo $record_id;?>";
  var type="<?php echo $type;?>";
  var filter="<?php echo $filter;?>";
  var allowedFileSize="<?php echo $allowedFileSize;?>";
  $(function () {
    var workflowOpen = "<?php echo $workflowOpen;?>";
  
    if (workflowOpen != 'all') {
      $('.nav-tabs a[href="#workflow' + workflowOpen + '"]').tab('show');
      var workflowId=$('.nav-tabs a[href="#workflow' + workflowOpen + '"]').attr("wid");
      $('#workflowId').val(workflowId);
    } else { 
      $('#myTab li:first-child a').tab('show');
      var workflowId=$('#myTab li:first-child a').attr("wid");
      $('#workflowId').val(workflowId);
    }
    var canUpdate=$('#canUpdate').val();
    if(canUpdate!='Yes'){
      $('#submitResetCancelButton').hide();
    } else {
      $('#submitResetCancelButton').show();
    }
  });
  var dateFormat = "<?php echo $dateFormat;?>";
  var dateTimeFormat = "<?php echo $dateTimeFormat;?>";
  var holidayList = '<?php echo json_encode($holidayList);?>';
</script>

<?php 
    $this->inlineScript()->appendFile($this->basePath() . '/js/module/asrtrace/workflow/workflowManagement.js', 'text/javascript');
    $this->inlineScript()->appendFile($this->basePath() . '/js/module/asrtrace/workflow/fieldTypeFunction.js', 'text/javascript');
    $this->inlineScript()->appendFile($this->basePath() . '/js/module/asrtrace/workflow/formulaFunctions.js', 'text/javascript');
 ?> 

<script>
   $(function () {
    <?php echo html_entity_decode($validation_script);?>
  });
</script>

 <style>
    .required:after { content:" *"; color: #e32; display:inline; }
</style>

<style>
  .disabled-picker {
      opacity: 0.7;
      pointer-events: none;
  }


  /* .load {
    left: 50%;
    margin-left: -4em;
  } */

  .loading {
    position: fixed;
    top: 0; right: 0;
    bottom: 0; left: 0;
    background: #fff;
  }
  .loader {
      left: 50%;
      margin-left: -4em;
      font-size: 10px;
      border: .8em solid rgba(218, 219, 223, 1);
      border-left: .8em solid rgba(58, 166, 165, 1);
      animation: spin 1.1s infinite linear;
  }
  .loader, .loader:after {
      border-radius: 50%;
      width: 8em;
      height: 8em;
      display: block;
      position: absolute;
      top: 50%;
      margin-top: -4.05em;
  }

  @keyframes spin {
    0% {
      transform: rotate(360deg);
    }
    100% {
      transform: rotate(0deg);
    }
  }
</style>